### ISSUE TITLE
gdk/gdkwayland.h

### ISSUE THREAD

**Issue by pequ7** [cemu-project/Cemu#571] opened 2022-12-11 11:17 UTC
As of v2.0.19 it is no longer possible to build cemu on gentoo. previous builds were succesfull.

Buid stage fails:

/Cemu/src/gui/../gui/helpers/wxWayland.h:6:10: fatal error: 'gdk/gdkwayland.h' file not found
#include <gdk/gdkwayland.h>

Can this be fixed ?

**Comment by jn64** [comment] 2022-12-11 14:36
Are you sure you're building 2.0-19 tag? Nothing changed between 2.0-18 and 2.0-19 re: wayland:

https://github.com/cemu-project/Cemu/compare/v2.0-18...v2.0-19

Wayland changes are after 2.0-19:

https://github.com/cemu-project/Cemu/compare/v2.0-19...main

---

Anyway I don't know gentoo, but that file should be provided by gtk3.

I guess you can use `equery` to find it?

**Comment by SupervisedThinking** [comment] 2022-12-12 00:53
The root cause is most likely https://github.com/cemu-project/Cemu/pull/553 since it does not include any CMake build opts to check if actually Wayland is supported on the target system. If it's X11 only the build will fail.

@SSimco ping

**Comment by pequ7** [comment] 2022-12-12 13:04
I am using git clone etc. I assumed this would be the latest version. 2.0.19.  I can see if cloning 2.0.19 is working. gtk is not build with wayland flag. I am not using wayland.

**Comment by jn64** [comment] 2022-12-12 14:10
If you clone from the URL without specifying a branch/tag/commit, you'll be on the main branch by default, at the latest commit, which is usually going to be newer than the last experimental version.

[On the 2.0-19 release](https://github.com/cemu-project/Cemu/releases/tag/v2.0-19), you can see it was built 12 days ago, and there's a little tag icon that says `v2.0-19`. In the folder you cloned, you can checkout that tag:

```shell
$ git checkout v2.0-19
```

Then you will be at the same commit used to build 2.0-19, before the recent Wayland changes. That should let you compile for now.

To return to the main branch, let's say after this issue is fixed, you can `git checkout main` (and of course, `git pull` to update).

For future reference, you can also [clone a specific tag](https://stackoverflow.com/questions/20280726/how-to-clone-a-specific-git-tag/21699307#21699307).

**Comment by pequ7** [comment] 2022-12-13 19:44
I checked my git clone. The issue is not with 2.0.19. So the issue is resolved until main becomes 2.0.20 ? Thank everyone looking in to this. Learned something too.

**Comment by SupervisedThinking** [comment] 2022-12-13 21:50
@pequ7 just clone single commits instead of tags last known good should be 2c81d240a5b065d8cf4c555754c4bfeaf42c826c - once https://github.com/cemu-project/Cemu/pull/572 will be merged it should work ootb **if** you disable `ENABLE_WAYLAND` in CMake opts.

**Closed** 2022-12-15 07:44 UTC

**Comment by Exzap** [comment] 2022-12-15 07:47
With the PR now merged you can pass `-DENABLE_WAYLAND=OFF` to cmake to avoid the dependency on Wayland.
