### ISSUE TITLE
Linux Differences from Windows

### ISSUE THREAD

**Issue by Ktoks** [cemu-project/Cemu#353] opened 2022-10-09 19:51 UTC
First of all, let me say that you're doing an awesome job getting this ported to native Linux!

I can't wait to see what it's like once polished up!

I'm running this on Vulkan, in Pop!_OS, high-end Nvidia, pulled and rebuilt the update, then reinstalled the game, patch, and DLC from scratch.

Bloom/lighting/shadows on Linux version do not follow the 'user graphics packs' like they do in windows as seen in window below - (colors are good, shadows are not accurate).

Both the following are to show shadow innaccuracies:
![new1](https://user-images.githubusercontent.com/36412717/194776670-78162ca1-ed99-4f8b-9306-6a59ca24d958.jpg)
![new2](https://user-images.githubusercontent.com/36412717/194776671-9a0b33a3-b4f2-4773-976a-07f0eba50e36.jpg)

Blooms have halos around sparks, flames, and light effects.

Death Mountain to show embers:
![new](https://user-images.githubusercontent.com/36412717/194776089-bc4e4597-4b8f-45e4-888c-71e907cac19c.jpg)

Blurring from heat is distorted. 

Translucent layers are boxy and take more resources.

I wish I could contribute, but I don't know how- I'm not a graphics guy, (though I am a software dev). Point me in the right direction and I could get dangerous though.

**Comment by Ktoks** [comment] 2022-10-09 19:52
After looking more closely at the blurring from heat- I think the effect is just too rapid and/or too small of an effect, if it were enlarged, it would look much more realistic.

**Comment by FishBulbish** [comment] 2022-10-14 22:28
I've noticed the "boxy" effect on translucent effects as well, it appears to only be a problem when not using the native graphics resolution.

I'm also not a graphics coder, but I'd be willing to bet having a reference photo taken in the windows version running via wine could help. Not an obligation, just an idea.

**Comment by Ktoks** [comment] 2022-10-16 19:06
I no longer use have and windows, so I can't provide one, unfortunately. See the repeat pixels around the embers? That's not supposed to be there.

Also, in the top 2 images, Link should be visible and not completely blacked out. He basically looks like a shadow running around in the dark. Not to mention darkness is ULTRA dark and any source of light is too bright.

**Comment by v-fox** [comment] 2022-10-23 19:46
Running fresh cemu build on Radeon RX580 with Mesa's radv driver and, so far, graphics are quite excellent and performance is more responsive when on yuzu, even with maxed out enhancements. Fps, while higher than yuzu, is still around 25-40 range instead unlocked of 60-72 with CPU & GPU load barely reaching 30% load, regardless if it's 720p or 1440p resolution. So, there is some kind of common bottleneck that is worse for yuzu but is still present here. Still better than native hardware though.

But this boxy artefact is kind of annoying, like a blemish over perfect picture.

> I've noticed the "boxy" effect on translucent effects as well, it appears to only be a problem when not using the native graphics resolution.

Do you mean native to original hardware (720p) or target PC ? Because it's good practice to set 125-200% of your native resolution and downsample rather than rely on ladder-ridden FXAA algorithm, so on PC is would rarely be native to either.

**Comment by gurrgur** [comment] 2022-10-29 09:26
As of #411 this issue should be resolved. #387 seems to be a duplicate of this, too.

The pixels around the embers are caused by the resolution patch being incomplete. When enabling higher resolutions in that BOTW graphic pack, it applies patches to the game code which worked fine already, however it also overrides some of the games shaders to account for the changed resolutions. Before #411 only code patches worked but custom shaders did not.

Clarity, bloom etc. also rely on custom shader overrides and should work as of 2.0-10.

**Closed** 2022-11-03 00:21 UTC
