### ISSUE TITLE
mario & sonic at the sochi 2014 olympics winter games crash with multicore recompiler mode and single core recompiler mode

### ISSUE THREAD

**Issue by yoshi200214** [cemu-project/Cemu#1295] opened 2024-08-16 17:08 UTC
### Current Behavior

the game mario & sonic at the sochi 2014 olympic winter games crash in title screen when use multicore recompiler cpu mode and single core recompiler.
when play the game in single core interpreter cpu mode the game not crash and goes to menus but the game runs slowly during the events

### Expected Behavior

is suppose to not crash on title screen and pass to menus

### Steps to Reproduce

1. play the game
2. see the intro
3. press a
4. 4. the game crash

### System Info (Optional)

OS: Windows 11
GPU: NVIDIA GeForce RTX 3060 Ti

### Emulation Settings (Optional)

Open gl api

### Logs (Optional)

[log.txt](https://github.com/user-attachments/files/16639606/log.txt)

**Comment by Squall-Leonhart** [comment] 2024-08-16 20:05
duplicate of issue #906

**Closed** 2024-08-18 22:39 UTC
Labels: bug
