### ISSUE TITLE
[Feature Request] Emulated Portal For Skylanders

### ISSUE THREAD

**Issue by KermitPrplYT** [cemu-project/Cemu#847] opened 2023-06-05 16:02 UTC

**Comment by KermitPrplYT** [comment] 2023-06-05 16:04
So my idea is a copy and paste from RPCS3 like how Dolphin basically did. I play on MacOS and whenever I play Skylanders Superchargers, I somehow cant connect my portal. and for figures i don't have, it would be nice to emulate those figures as well. Even though this is like an "Easier Said Than Done" Situation.

**Comment by Exzap** [comment] 2023-06-05 16:13
Duplicate of #588

**Closed by Exzap** 2023-06-05 16:13 UTC
