### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Doomsdayrs** [cemu-project/Cemu#22] opened 2022-08-24 17:27 UTC
Flatpak will allow cemu to be used on all linux distributions.

Would be nice:
- #20

**Comment by Doomsdayrs** [comment] 2022-08-24 18:36
Alright, why does Cemu need SEPol?

**Comment by JakobDev** [comment] 2022-08-24 18:59
You should maybe wait until Cemu is ready. There are a few major Issues like that it needs a case-insensitive filesystem. Iaslo have 2 PRs (#12 and #10)  open for the data files, so you don't need to create your own.

**Comment by Doomsdayrs** [comment] 2022-08-24 19:30
> You should maybe wait until Cemu is ready. 

Precisely why it is a draft pr :D

> There are a few major Issues like that it needs a case-insensitive filesystem. 

CEMO is not case sensitive ready?

> Iaslo have 2 PRs (#12 and #10) open for the data files, so you don't need to create your own.

I will look at them, and see how to get them imported into the flatpak on compilation time (of the flatpak)

**Comment by JakobDev** [comment] 2022-08-24 21:07
> CEMO is not case sensitive ready?

See #1

> I will look at them, and see how to get them imported into the flatpak on compilation time (of the flatpak)

You just need to wait until they got merged

**Comment by Eonfge** [comment] 2022-08-26 15:04
As mentioned in #1, 

I did some quick work for a Flatpak but the first problem that has to be tackle VCPKG. It's not very suitable for the reproducible and isolated build standard of Flatpaks: The VCPKG-package fails because it tries to connect with the network within the build process which is running in an isolated environment.

https://github.com/Eonfge/flathub/tree/info.cemu.Cemu 

This should first be resolved before we can continue with a Flatpak

**Comment by Crementif** [comment] 2022-08-29 07:22
Flatpak is no longer required since #75 was merged.

**Comment by Tachi107** [comment] 2022-08-29 08:00
> As mentioned in #1, 
> 
> I did some quick work for a Flatpak but the first problem that has to be tackle VCPKG. It's not very suitable for the reproducible and isolated build standard of Flatpaks: The VCPKG-package fails because it tries to connect with the network within the build process which is running in an isolated environment.
> 
> https://github.com/Eonfge/flathub/tree/info.cemu.Cemu 
> 
> This should first be resolved before we can continue with a Flatpak

This has been fixed in #75; the build can be now completed without using vcpkg (only system dependencies)

**Comment by Doomsdayrs** [comment] 2022-08-31 17:18
Had to disable vcpkg for the flatpak build, as flatpak does not allow network access during build time.

```yaml
      - -DENABLE_VCPKG=false
```

**Comment by Tachi107** [comment] 2022-09-07 08:15
Cemu's Findimgui.cmake file already checks for both a pkg-config file and a CMake Config file, usually provided by distros. What issue are you facing?

**Comment by Doomsdayrs** [comment] 2022-09-07 13:00
> Cemu's Findimgui.cmake file already checks for both a pkg-config file and a CMake Config file, usually provided by distros. What issue are you facing?

I cannot use vcpkg for flatpak, the dependencies have to be specified implicitly.

**Comment by Tachi107** [comment] 2022-09-07 13:12
I know you cannot use vcpkg. What I meant is that is that the Findimgui.cmake file can find imgui if it is installed on the host system (for example, when installing the `libimgui-dev` package on Debian).

What environment do you have to use to build Flatpaks?

**Comment by Eonfge** [comment] 2022-09-07 15:46
I've been keeping up to date, and this should be the next step in getting a working Flatpak Cemu. Latest version has `-DENABLE_VCPKG=false`, full llvm12 (clang-12) and so forth.


https://github.com/Eonfge/flathub/tree/info.cemu.Cemu

**Comment by istori1** [comment] 2022-09-13 11:16
> Had to disable vcpkg for the flatpak build, as flatpak does not allow network access during build time.
> 
> ```yaml
>       - -DENABLE_VCPKG=false
> ```

Something like this will enable the use of network for vcpkg

`modules:
  - name: vcpkg
    build-options:
      build-args:
        - --share=network`

**Comment by SSimco** [comment] 2022-09-18 21:04
I've made a working Flatpak Cemu that kinda works, but it crashes sometimes for me when I open the graphic packs menu and try to change anything. Maybe I will find a fix for that later.
https://github.com/SSimco/flathub/tree/info.cemu.Cemu

**Comment by Doomsdayrs** [comment] 2022-09-18 21:44
@SSimco Since I lacked the time to contribute for this enough, can you make the PR to flathub?

**Comment by JakobDev** [comment] 2022-09-19 05:57
It would make sense to upstream the patches.

**Comment by j8r** [comment] 2022-10-08 16:42
Hello, good news: I got a fully flathub-compliant Flatpak built. However, the application quickly returns an error after startup stating that some directory are not writable. It can be fixed by complying with the XDG directory standard.

Now remains to contribute to Cemu to make application run properly inside Flatpak, be free to work on it :slightly_smiling_face: . 
[Here is the Flatpak source code](https://github.com/j8r/flathub/tree/info.cemu.Cemu) along with the build instructions for those wanting to work on it.

Here are the AUR files along with their patches, which can be helpful - all credits to them: https://aur.archlinux.org/cgit/aur.git/tree/?h=cemu

Thanks to @Anuskuss, @Doomsdayrs and @Eonfge for their work, which helped me to make the package.

Some questions:
- Why https://github.com/cemu-project/Cemu/blob/main/src/resource/logo_1.png is 241x241, not 256x256? Also the naming scheme can be more robust, for example by suffixing the px numbers. More image resolutions will be also welcome: 16, 32, 48, 64, 128 and 512, plus a svg if you can.
- Only the `filesystem,nowide,program_options,system` boost libraries have been necessary. Others defined in https://github.com/cemu-project/Cemu/blob/main/vcpkg.json could potentially be removed (to be tested)

**Comment by Exzap** [comment] 2022-10-08 19:14
Oh good work!
I started to look into flatpak myself recently because this PR seemed stale. While working on it I also fixed some issues with our build system so that we don't require as many patches and workarounds for building the flatpak. (Ideally none at all) 

Since I got pretty far already I think the best course of action is to merge our work and then I can submit it to flathub under the name of our organization (cemu-project). Assuming you don't mind?

> However, the application quickly returns an error after startup stating that some directory are not writable. It can be fixed by complying with the XDG directory standard.

There have been some PRs for this already. A recent one was pretty promising but the author closed it without comment. I'll look into this.

> Why https://github.com/cemu-project/Cemu/blob/main/src/resource/logo_1.png is 241x241, not 256x256? Also the naming scheme can be more robust, for example by suffixing the px numbers. More image resolutions will be also welcome: 16, 32, 48, 64, 128 and 512, plus a svg if you can.

No particular reason other than we don't have the logo in a higher resolution and the original artist has long disappeared. Someone would have to remake it if we wanted it as SVG or in much higher resolution since upscaling can only get us so far.

> Only the filesystem,nowide,program_options,system boost libraries have been necessary. Others defined in https://github.com/cemu-project/Cemu/blob/main/vcpkg.json could potentially be removed (to be tested)

We definitively use more than that. Keep in mind that boost modules often have dependencies on other boost modules and you indirectly get more modules than you ask for. When I wrote the list for vcpkg.json I went through all the included boost modules in our source so there shouldn't be any unnecessary ones.

**Comment by j8r** [comment] 2022-10-08 19:33
Thanks for the quick reply!
Great, awesome if you can work on that!
For the name, it is a reverse domain name.
The Cemu project owns the cemu.info domain, so the app name will start with `info.cemu`.
I suspect it can be `info.cemu.cemu-project.Cemu` instead of `info.cemu.Cemu` if you prefer.
It can also be `com.github.cemu-project.Cemu`.

I don't know if you know how the flathub submission work? It doesn't matter much at the end who submit.
I can let you fork my repository and make any modification deemed necessary.
You'll have admin rights to the future flathub repository of course anyways.

**Comment by j8r** [comment] 2022-10-08 19:35
> No particular reason other than we don't have the logo in a higher resolution and the original artist has long disappeared. Someone would have to remake it if we wanted it as SVG or in much higher resolution since upscaling can only get us so far.

I guess it is the perfect time for a new logo contest 😄

**Comment by JakobDev** [comment] 2022-10-08 20:00
> The Cemu project owns the cemu.info domain, so the app name will start with info.cemu.
> I suspect it can be info.cemu.cemu-project.Cemu instead of info.cemu.Cemu if you prefer.
> It can also be com.github.cemu-project.Cemu.

The App ID is already set: It's `info.cemu.Cemu`, like the name of the Linux dist files. It was discussed back then. btw: ID's that start with `com.github` are no longer allowe3d on Flathub.

> There have been some PRs for this already. A recent one was pretty promising but the author closed it without comment. I'll look into this.

Sounds good. I hope that we will get a Flatpak soon.

**Comment by j8r** [comment] 2022-10-08 20:16
Oh ok so @Exzap meant submitting the PR from https://github.com/cemu-project/flathub/tree/info.cemu.Cemu, my bad.
No problem!

**Comment by cobalt2727** [comment] 2022-10-08 21:02
> No particular reason other than we don't have the logo in a higher resolution and the original artist has long disappeared. Someone would have to remake it if we wanted it as SVG or in much higher resolution since upscaling can only get us so far.

@Exzap Wikipedia seems to have a 512x512 version, no idea if this is official or not: https://en.m.wikipedia.org/wiki/File:Cemu_Emulator_icon.png

**Comment by ludg1e** [comment] 2022-10-08 21:39
> > No particular reason other than we don't have the logo in a higher resolution and the original artist has long disappeared. Someone would have to remake it if we wanted it as SVG or in much higher resolution since upscaling can only get us so far.
> 
> @Exzap Wikipedia seems to have a 512x512 version, no idea if this is official or not: https://en.m.wikipedia.org/wiki/File:Cemu_Emulator_icon.png

Seems to be a recreation from a guy, here's his DevianArt page: https://www.deviantart.com/we4ponx
![image](https://user-images.githubusercontent.com/77110723/194728614-ba876002-a83e-4957-8b30-ff5c5d3eb1f0.png)

Although maybe an new logo contest would be better

**Comment by j8r** [comment] 2022-10-08 21:53
Let's use that then, if the Cemu authors agree. It seems not copyrightable, thus free for any use.

**Comment by jibsaramnim** [comment] 2022-10-25 07:03
> However, the application quickly returns an error after startup stating that some directory are not writable. It can be fixed by complying with the XDG directory standard.

@j8r I was able to avoid this problem by compiling Cemu with `PORTABLE` set to `OFF` (this defaults to `ON`). With it off, it will actually already use XDG standard directories. It also seems like more recent commits of Cemu remove the need for the included `glslang-spriv.patch`.

Here's a diff of your repo's work, in case it helps. It has a few other changes to get things to compile locally, as it was referencing some specific commit branch combinations that have since become outdated/desynced. I also enabled `--filesystem=home` so that Cemu would actually have access to the home directory, and I also switched to the `Release` build type, but that wasn't strictly necessary to get things to build.

```patch
diff --git a/info.cemu.Cemu.yml b/info.cemu.Cemu.yml
index 754b7fa..f31fdb0 100644
--- a/info.cemu.Cemu.yml
+++ b/info.cemu.Cemu.yml
@@ -11,6 +11,7 @@ finish-args:
   - --device=all
   - --socket=pulseaudio
   - --share=network
+  - --filesystem=home
 
 modules:
   - name: boost
@@ -35,7 +36,7 @@ modules:
     cleanup:
       - /lib/*.a
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
     sources:
       - type: archive
         url: https://github.com/fmtlib/fmt/archive/refs/tags/9.1.0.tar.gz
@@ -48,19 +49,19 @@ modules:
   - name: glm
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
     sources:
       - type: git
         url: https://github.com/g-truc/glm.git
         branch: master
-        commit: cc98465e3508535ba8c7f6208df934c156a018dc
+        #commit: 0a6d3334ea747b0023d232572d3aff61dc6b48e6
 
   - name: glslang
     buildsystem: cmake-ninja
     cleanup:
       - /lib/*.a
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
       - -DBUILD_EXTERNAL=OFF
       - -DBUILD_SHARED_LIBS=ON
       - -DSKIP_GLSLANG_INSTALL=OFF
@@ -77,14 +78,13 @@ modules:
   - name: imgui
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
     cleanup:
       - /lib/*.a
     sources:
       - type: git
         url: https://github.com/ocornut/imgui.git
         tag: v1.88
-        commit: 9aae45eb4a05a5a1f96be1ef37eb503a12ceb889
         x-checker-data:
           type: json
           url: https://api.github.com/repos/ocornut/imgui/releases/latest
@@ -101,7 +101,7 @@ modules:
   - name: libzip
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
       - -DBUILD_DOC=OFF
     cleanup:
       - /bin
@@ -118,7 +118,7 @@ modules:
   - name: pugixml
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
       - -DBUILD_SHARED_LIBS=ON
     sources:
       - type: archive
@@ -132,7 +132,7 @@ modules:
   - name: rapidjson
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
       - -DRAPIDJSON_BUILD_DOC=OFF
       - -DRAPIDJSON_BUILD_EXAMPLES=OFF
       - -DRAPIDJSON_BUILD_TESTS=OFF
@@ -148,7 +148,7 @@ modules:
   - name: wxwidgets
     buildsystem: cmake-ninja
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
     cleanup:
       - /bin
       - /include
@@ -157,7 +157,6 @@ modules:
       - type: git
         url: https://github.com/wxWidgets/wxWidgets
         tag: v3.2.1
-        commit: 97e99707c5d2271a70cb686720b48dbf34ced496
         x-checker-data:
           type: anitya
           project-id: 5150
@@ -170,17 +169,15 @@ modules:
     buildsystem: cmake-ninja
     builddir: true
     config-opts:
-      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
+      - -DCMAKE_BUILD_TYPE=Release
       - -DENABLE_VCPKG=OFF
+      - -DPORTABLE=OFF
     post-install:
-      - install -m755 ../bin/Cemu_relwithdebinfo $FLATPAK_DEST/bin/Cemu
+      - install -m755 ../bin/Cemu_release $FLATPAK_DEST/bin/Cemu
       - install -Dm644 ../src/resource/logo_icon.png $FLATPAK_DEST/share/icons/hicolor/128x128/apps/info.cemu.Cemu.png
       - install -Dm644 ../dist/linux/info.cemu.Cemu.desktop $FLATPAK_DEST/share/applications/info.cemu.Cemu.desktop
       - install -Dm644 ../dist/linux/info.cemu.Cemu.metainfo.xml $FLATPAK_DEST/share/metainfo/info.cemu.Cemu.metainfo.xml
     sources:
       - type: git
         url: https://github.com/cemu-project/Cemu.git
-        # branch: master
-        commit: b724a657e6b33e011808dbc4a398a344c4f7593d
-      - type: patch
-        path: glslang-spriv.patch
+        tag: v2.0-8
\ No newline at end of file
```

**Comment by j8r** [comment] 2022-10-25 11:06
Thanks to have tried it out! Being able to write to the home is not a solution, it defeats the whole purpose of the sandbox, plus is not necessary if the application is designed properly. I'll add `host:ro` to access the roms. 

`RelWithDebInfo` should also be kept, can be useful for debugging, and otherwise the flatpak linter will flag those.

The remaining change is `PORTABLE=ON` then, the executable name and removing the patch. Thanks to have pointed me to that!

@Exzap

**Comment by j8r** [comment] 2022-10-25 11:07
Thanks to have tried it out! Being able to write to the home is not a solution, it defeats the whole purpose of the sandbox, plus is not necessary if the application is designed properly. I'll add `host:ro` to access the roms. 

`RelWithDebInfo` should also be kept, can be useful for debugging, and otherwise the flatpak linter will flag those.

The remaining change is `PORTABLE=ON` then, the executable name and removing the patch. Thanks to have pointed me to that!

**Comment by Doomsdayrs** [comment] 2022-10-25 11:40
> Thanks to have tried it out! Being able to write to the home is not a solution, it defeats the whole purpose of the sandbox, plus is not necessary if the application is designed properly. I'll add `host:ro` to access the roms.

I think its better to just upstream using xdg portals.

**Comment by Exzap** [comment] 2022-10-25 12:19
Hey just some update to avoid anyone doing duplicate work.
I got the flatpak to build locally a week ago and it runs fine on my Steam Deck. Zero patches are required. I'll upload it to a repo soon. @emiyl also made a new high res logo that we can use.

However, I think that the Linux build of Cemu just isn't ready to be widely distributed yet, at least on flathub where the user expects working software. There are still some problems that need to be resolved:
- At least with `host:ro` setting a custom mlc folder will prevent Cemu from working due to expecting write-access. Portals should solve this but for some reason I couldn't see my premade mlc or game directories within the sandboxed directory dialog.
- The flatpak currently ignores the users theme. I tried the workarounds that come up with a quick google search but none worked.
- Assuming the above problem is fixed, on dark themes parts of Cemu's UI are unusable due to white text on white background.
- Online features are still stubbed on Linux/MacOS
- HID and USB code is stubbed so no support for Skylander/Lego portals or Gamecube controllers
- For user convenience we should have UI options to open log.txt, delete shader cache and some other operations that people usually do by manually accessing files. 
- Issues with keyboard input not recognizing all keys
- Probably lots of smaller regressions that I didn't even discover yet

> RelWithDebInfo should also be kept, can be useful for debugging, and otherwise the flatpak linter will flag those.

I tried `RelWithDebInfo` and `Release`, for some reason they both give me the same amount of debug info. Doesn't happen when built outside of flatpak-builder

**Comment by felipecrs** [comment] 2022-10-25 12:56
> However, I think that the Linux build of Cemu just isn't ready to be widely distributed yet, at least on flathub where the user expects working software.

It may be a good fit for Flathub Beta.

**Comment by jibsaramnim** [comment] 2022-10-25 13:01
> Being able to write to the home is not a solution, it defeats the whole purpose of the sandbox, plus is not necessary if the application is designed properly. I'll add `host:ro` to access the roms.

It was mostly added for my own ability to test things out, so I could link to my existing mlc folder without having to move it around. Taking a quick gander at how some of the other emulators available on Flathub do it, it seems like giving read-only access to home is the common choice. Perhaps we can adopt the same?

> `RelWithDebInfo` should also be kept, can be useful for debugging, and otherwise the flatpak linter will flag those.

I followed Cemu’s own documentation which specifies `Release`, but I’ll leave it up to those that know more about this to figure out which one is the right one.

> The remaining change is `PORTABLE=ON` then, the executable name and removing the patch. Thanks to have pointed me to that!

My pleasure! Thanks so much for having worked on this so far, it’s going to be fantastic once people can easily install Cemu through flatpaks. Good times are coming!

> However, I think that the Linux build of Cemu just isn't ready to be widely distributed yet, at least on flathub where the user expects working software. There are still some problems that need to be resolved

I believe there is a way to have it available as a beta, meaning not directly visible through the site, but it is installable for those who know what they’re up for. 

If others also feel that publishing Cemu on Flathub as-is would not be good just yet, I would like to drop a strong vote for this beta route at least, as it already is very usable. 

For what it’s worth, I personally don’t think it’s a big deal to have it be fully published, with  mention of features that might not exist in this build as compared to the Windows version. 

Giving those that want to use it a way to do this more easily, without having to build things themselves (which could be challenging on certain devices/environments) would absolutely be worth it in my book.

**Comment by j8r** [comment] 2022-10-25 14:30
In most other emulators, `host:ro` for two reasons: the application doesn't implement portals, and second in any case to allow roms to be opened when running the application from the CLI. Users can also have roms in `/mnt`, `/media`.
Play! allows `home:ro`, `/mnt:ro`, `/media:ro` and `/run/media:ro`, which is another option.

There is also the `- --persist=.` option, which steam uses.
I'm not familiar with the mlc folder, I think it could be better to store in a XDG directory instead of asking the user (portals).

> I tried RelWithDebInfo and Release, for some reason they both give me the same amount of debug info. Doesn't happen when built outside of flatpak-builder

Maybe, at least the important part is it won't matter at the end: the built binary will still be built with release optimizations.

Indeed I also think submitting to Flathub is premature, but IMO only blocking issues can be sorted out before releasing it: i.e. being able to play, but theming is not a big deal for instance.

**Comment by Tachi107** [comment] 2022-10-25 21:47
> Play! allows home:ro, /mnt:ro, /media:ro and /run/media:ro, which is another option.

Is a whitelist worth it? Most sensitive data is in the home directory anyway.

**Comment by j8r** [comment] 2022-10-26 01:38
Agreed, in the other flatpaked emulators I've just set `--filesystem=host:ro`.

**Comment by jibsaramnim** [comment] 2022-11-09 05:08
> The remaining change is `PORTABLE=ON` then, **the executable name** and removing the patch.

Small update to this; it seems like the executable has now been renamed to being capitalized ([see here](https://github.com/cemu-project/Cemu/commit/4561a6929cf5f0f8141898d05b60353e1234e9d9)), so the executable name change is no longer necessary.

One more possible addition; I thought I'd mention this just in case it's not just for me and my environment, but the `rapidjson` build started failing with a `transport 'file' not allowed` error for one of its submodules. Setting `git config --global protocol.file.allow always` fixes this, should this come up for others too, so might have to be set as part of the flatpak build.

**Comment by j8r** [comment] 2023-01-04 15:19
I updated the [Cemu Flatpak](https://github.com/j8r/flathub/tree/info.cemu.Cemu), it compiles now with the latest commit. However, running it returns a warning window saying: "Cemu can't write to /app/bin".

**Comment by JakobDev** [comment] 2023-01-04 16:36
Try to disable to [portable option](https://github.com/cemu-project/Cemu/blob/33bd10b4e0b9c27881fa7d6bf38908791f84d3b2/CMakeLists.txt#L4)

**Comment by j8r** [comment] 2023-01-04 17:14
I forgot about that. Cemu opens now :slightly_smiling_face: 
Would be great to have an option to avoid the linking of the static archives like `src/asm/libCemuAsm.a`, which slows down the compilation and use a **lot** of memory.

**Comment by Tachi107** [comment] 2023-01-04 19:47
Il giorno mer 4 gen 2023 alle 09:15:13 -08:00:00, Julien Reichardt 
***@***.***> ha scritto:
> Would be great to have an option to avoid the linking of the static 
> archives like src/asm/libCemuAsm.a, which slows down the compilation 
> and use a lot of memory.
> 

What do you mean? As far as I know they are core parts of Cemu and 
cannot be avoided.

**Comment by j8r** [comment] 2023-01-04 20:52
I thought it may be a static archive, which are usually used to statically link against libraries, but it doesn't seems to be the case here so nevermind.

**Comment by anonyme-x22** [comment] 2023-01-14 22:34
Yes please make an official flat/snap channel so we can have automatic upgrade and standard app install/management for the distro!

**Comment by mrjpaxton** [comment] 2023-02-02 12:12
Okay, I'm really glad that this exists. I've been wanting a Flathub version of this, but I know that Flatpak has its own technical issues, and I might even see how annoying more "niche" things like gryo and networking support might be a problem, especially since you can't access Linux udev devices directly.

Anyway, is someone still looking for new logo ideas? I wrote a mockup logo. Since the Wii U is also called Project Cafe, I thought I'd go ahead and suggest a cafe mug: https://i.imgur.com/6gPTi5W.png

At first it had steam coming out of the logo, but I replaced it with a controller. However, I thought the logo looked way too busy. I also saw a "face" on it. Not really a great look.

But I simplified it down, and how it looks like this: https://i.imgur.com/M4qEDn9.png

If anyone more experienced with Inkscape can draw/trace an SVG out of this if it looks okay, that might be a good idea. Maybe center it. A black border could be optional. I know the original Wii U logo did not have a black border, but there's nothing against doing it.

I just really don't want people to think it's a Java application though, just because it uses a coffee mug, that'd be really disrespectful to a fantastic C/C++ project. :p

**Comment by mrjpaxton** [comment] 2023-02-02 12:33
https://i.imgur.com/l4XcBwj.png

Okay fine, I absolutely wanted the gray coffee plate under it. I think it adds to an already great look. It's about the same colors as the Wii U logo, but it can always be color corrected.

If the maintainers want to approve it, I'll try to learn how to use Inkscape again and make this myself somehow.

**Comment by Exzap** [comment] 2023-03-25 22:53
We now have a flatpak, thanks to the work done by @ColinKinloch!
https://github.com/flathub/info.cemu.Cemu
https://flathub.org/apps/details/info.cemu.Cemu

Closing this as the original request has been fullfilled. If anyone runs into problems with the flatpak (that aren't present in the native/appimage build) then please open an issue over on the [flathub Cemu repo](https://github.com/flathub/info.cemu.Cemu)

**Closed by Exzap** 2023-03-25 22:53 UTC
Labels: feature request, build related
