### ISSUE TITLE
[Bug] Cemu crashes in every Skylanders game with a connected portal of power

### ISSUE THREAD

**Issue by Miaush** [cemu-project/Cemu#1058] opened 2024-01-07 20:41 UTC
I wanted to play Skylanders again after some time and Cemu updates.
For me the bug happened on Cemu 2.0-61, the latest version right now, and according to a reddit post I've found is „fixable“ by downgrading to 2.0-47, in which version the games don't crash after selecting a language or even before that.

Steps to reproduce:

1. Connect Portal of Power and install the drivers in device manager (USB Input Device)
1.5. Try to launch a game without the portal connected to see if it crashes. It should not crash but rather show the message to connect a portal.
2. Launch the game. It will now crash if you are using one of the newer Cemu versions (every version since 2.0-47 probably)

This crash has nothing to do with the crash happening when using Superchargers/Imaginators + the Updates with an Online Account. (just disable online mode to fix it)

Until now I couldn't really find anything useful in the logs, but it probably has something to do with changes to the way USB devices are handled by cemu.

The only fix for me was to downgrade the Cemu version to 2.0-47.

I have tested all of the 6 games with the newest Cemu version, and the bug is present in every game and at the exact same point. Either after selecting a language for the games that support multiple languages, or directly on launch.

**Comment by TheRealWario** [comment] 2024-01-08 02:42
Its a known issue. Indeed, this is caused by a PR that attempted to change the usb support to be usable with zadig drivers, like dolphin has. Unfortunately, as you seem to have noticed, it broke the functionality entirely. It needs someone to look into it, but it may be a while.

**Comment by Squall-Leonhart** [comment] 2024-01-08 03:11
You can close this, the issue as stated is known and the fix is included in a changeset in the PR already.

**Closed** 2024-01-08 04:55 UTC
