### ISSUE TITLE
Crash on macOS Ventura when starting a game.

### ISSUE THREAD

**Issue by NalyAh08** [cemu-project/Cemu#301] opened 2022-09-25 12:53 UTC
When starting a game (installed from meta.xml) the game crashes as soon as you click on the game. This is on the M1 Mac with 8GB RAM (MacBook Air) running macOS 13 (Ventura). Terminal gives this output when starting a game.

> No bundle id found
> zsh: illegal hardware instruction  /Users/nalyahmad/Documents/Games/Wii\ U/Cemu\ Emulator/Cemu
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]

Is this an issue with Ventura or am I doing something wrong?

**Comment by NalyAh08** [comment] 2022-09-25 13:12
Update : Following the guide from a previous issue request, I was able to enable Vulkan in the graphical settings, using this guide from a user called "vesper8".

> # install x64 brew
> arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
> 
> # create an alias ibrew (optional)
> alias ibrew='arch -x86_64 /usr/local/bin/brew'
> 
> # install x64 dependencies using your new x64 brew with the alias
> ibrew install molten-vk
> 
> # or
> arch -x86_64 /usr/local/bin/brew install molten-vk

Some games work however one game, specifically "Minecraft Wii U Edition" does not launch.

> No bundle id found
> 2022-09-25 14:08:54.058 Cemu[5663:75377] +[CATransaction synchronize] called within transaction
> [mvk-info] MoltenVK version 1.1.11, supporting Vulkan version 1.1.224.
> 	The following 81 Vulkan extensions are supported:
> 		VK_KHR_16bit_storage v1
> 		VK_KHR_8bit_storage v1
> 		VK_KHR_bind_memory2 v1
> 		VK_KHR_buffer_device_address v1
> 		VK_KHR_create_renderpass2 v1
> 		VK_KHR_dedicated_allocation v3
> 		VK_KHR_depth_stencil_resolve v1
> 		VK_KHR_descriptor_update_template v1
> 		VK_KHR_device_group v4
> 		VK_KHR_device_group_creation v1
> 		VK_KHR_driver_properties v1
> 		VK_KHR_dynamic_rendering v1
> 		VK_KHR_external_fence v1
> 		VK_KHR_external_fence_capabilities v1
> 		VK_KHR_external_memory v1
> 		VK_KHR_external_memory_capabilities v1
> 		VK_KHR_external_semaphore v1
> 		VK_KHR_external_semaphore_capabilities v1
> 		VK_KHR_fragment_shader_barycentric v1
> 		VK_KHR_get_memory_requirements2 v1
> 		VK_KHR_get_physical_device_properties2 v2
> 		VK_KHR_get_surface_capabilities2 v1
> 		VK_KHR_imageless_framebuffer v1
> 		VK_KHR_image_format_list v1
> 		VK_KHR_maintenance1 v2
> 		VK_KHR_maintenance2 v1
> 		VK_KHR_maintenance3 v1
> 		VK_KHR_multiview v1
> 		VK_KHR_portability_subset v1
> 		VK_KHR_push_descriptor v2
> 		VK_KHR_relaxed_block_layout v1
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_sampler_ycbcr_conversion v14
> 		VK_KHR_separate_depth_stencil_layouts v1
> 		VK_KHR_shader_draw_parameters v1
> 		VK_KHR_shader_float16_int8 v1
> 		VK_KHR_shader_subgroup_extended_types v1
> 		VK_KHR_storage_buffer_storage_class v1
> 		VK_KHR_surface v25
> 		VK_KHR_swapchain v70
> 		VK_KHR_swapchain_mutable_format v1
> 		VK_KHR_timeline_semaphore v2
> 		VK_KHR_uniform_buffer_standard_layout v1
> 		VK_KHR_variable_pointers v1
> 		VK_EXT_buffer_device_address v2
> 		VK_EXT_debug_marker v4
> 		VK_EXT_debug_report v10
> 		VK_EXT_debug_utils v2
> 		VK_EXT_descriptor_indexing v2
> 		VK_EXT_fragment_shader_interlock v1
> 		VK_EXT_hdr_metadata v2
> 		VK_EXT_host_query_reset v1
> 		VK_EXT_image_robustness v1
> 		VK_EXT_inline_uniform_block v1
> 		VK_EXT_memory_budget v1
> 		VK_EXT_metal_objects v1
> 		VK_EXT_metal_surface v1
> 		VK_EXT_post_depth_coverage v1
> 		VK_EXT_private_data v1
> 		VK_EXT_robustness2 v1
> 		VK_EXT_sample_locations v1
> 		VK_EXT_scalar_block_layout v1
> 		VK_EXT_separate_stencil_usage v1
> 		VK_EXT_shader_stencil_export v1
> 		VK_EXT_shader_viewport_index_layer v1
> 		VK_EXT_subgroup_size_control v2
> 		VK_EXT_swapchain_colorspace v4
> 		VK_EXT_texel_buffer_alignment v1
> 		VK_EXT_texture_compression_astc_hdr v1
> 		VK_EXT_vertex_attribute_divisor v3
> 		VK_AMD_gpu_shader_half_float v2
> 		VK_AMD_negative_viewport_height v1
> 		VK_AMD_shader_image_load_store_lod v1
> 		VK_AMD_shader_trinary_minmax v1
> 		VK_IMG_format_pvrtc v1
> 		VK_INTEL_shader_integer_functions2 v1
> 		VK_GOOGLE_display_timing v1
> 		VK_MVK_macos_surface v3
> 		VK_MVK_moltenvk v35
> 		VK_NV_fragment_shader_barycentric v1
> 		VK_NV_glsl_shader v1
> [mvk-info] GPU device:
> 		model: Apple M1
> 		type: Integrated
> 		vendorID: 0x106b
> 		deviceID: 0xd0003ef
> 		pipelineCacheUUID: 0000277F-0D00-03EF-0000-000000000000
> 	supports the following Metal Versions, GPU's and Feature Sets:
> 		Metal Shading Language 2.4
> 		GPU Family Apple 7
> 		GPU Family Apple 6
> 		GPU Family Apple 5
> 		GPU Family Apple 4
> 		GPU Family Apple 3
> 		GPU Family Apple 2
> 		GPU Family Apple 1
> 		GPU Family Mac 2
> 		GPU Family Mac 1
> 		GPU Family Common 3
> 		GPU Family Common 2
> 		GPU Family Common 1
> 		macOS GPU Family 2 v1
> 		macOS GPU Family 1 v4
> 		macOS GPU Family 1 v3
> 		macOS GPU Family 1 v2
> 		macOS GPU Family 1 v1
> [mvk-info] Created VkInstance for Vulkan version 1.1.224, as requested by app, with the following 3 Vulkan extensions enabled:
> 		VK_KHR_surface v25
> 		VK_EXT_debug_utils v2
> 		VK_EXT_metal_surface v1
> [mvk-info] Using emulation for Vulkan semaphores.
> [mvk-info] Created VkDevice to run on GPU Apple M1 with the following 3 Vulkan extensions enabled:
> 		VK_KHR_driver_properties v1
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_swapchain v70
> [mvk-info] Created 3 swapchain images with initial size (1280, 720) and contents scale 1.0 for screen Built-in Retina Display.
> zsh: bus error  /Users/nalyahmad/Documents/Games/Wii\ U/Cemu\ Emulator/Cemu
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]

**Comment by NalyAh08** [comment] 2022-09-25 14:37
After further testing, other games display a different error, it loads the loading screen then crashes. 

> No bundle id found
> [mvk-info] MoltenVK version 1.1.11, supporting Vulkan version 1.1.224.
> 	The following 81 Vulkan extensions are supported:
> 		VK_KHR_16bit_storage v1
> 		VK_KHR_8bit_storage v1
> 		VK_KHR_bind_memory2 v1
> 		VK_KHR_buffer_device_address v1
> 		VK_KHR_create_renderpass2 v1
> 		VK_KHR_dedicated_allocation v3
> 		VK_KHR_depth_stencil_resolve v1
> 		VK_KHR_descriptor_update_template v1
> 		VK_KHR_device_group v4
> 		VK_KHR_device_group_creation v1
> 		VK_KHR_driver_properties v1
> 		VK_KHR_dynamic_rendering v1
> 		VK_KHR_external_fence v1
> 		VK_KHR_external_fence_capabilities v1
> 		VK_KHR_external_memory v1
> 		VK_KHR_external_memory_capabilities v1
> 		VK_KHR_external_semaphore v1
> 		VK_KHR_external_semaphore_capabilities v1
> 		VK_KHR_fragment_shader_barycentric v1
> 		VK_KHR_get_memory_requirements2 v1
> 		VK_KHR_get_physical_device_properties2 v2
> 		VK_KHR_get_surface_capabilities2 v1
> 		VK_KHR_imageless_framebuffer v1
> 		VK_KHR_image_format_list v1
> 		VK_KHR_maintenance1 v2
> 		VK_KHR_maintenance2 v1
> 		VK_KHR_maintenance3 v1
> 		VK_KHR_multiview v1
> 		VK_KHR_portability_subset v1
> 		VK_KHR_push_descriptor v2
> 		VK_KHR_relaxed_block_layout v1
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_sampler_ycbcr_conversion v14
> 		VK_KHR_separate_depth_stencil_layouts v1
> 		VK_KHR_shader_draw_parameters v1
> 		VK_KHR_shader_float16_int8 v1
> 		VK_KHR_shader_subgroup_extended_types v1
> 		VK_KHR_storage_buffer_storage_class v1
> 		VK_KHR_surface v25
> 		VK_KHR_swapchain v70
> 		VK_KHR_swapchain_mutable_format v1
> 		VK_KHR_timeline_semaphore v2
> 		VK_KHR_uniform_buffer_standard_layout v1
> 		VK_KHR_variable_pointers v1
> 		VK_EXT_buffer_device_address v2
> 		VK_EXT_debug_marker v4
> 		VK_EXT_debug_report v10
> 		VK_EXT_debug_utils v2
> 		VK_EXT_descriptor_indexing v2
> 		VK_EXT_fragment_shader_interlock v1
> 		VK_EXT_hdr_metadata v2
> 		VK_EXT_host_query_reset v1
> 		VK_EXT_image_robustness v1
> 		VK_EXT_inline_uniform_block v1
> 		VK_EXT_memory_budget v1
> 		VK_EXT_metal_objects v1
> 		VK_EXT_metal_surface v1
> 		VK_EXT_post_depth_coverage v1
> 		VK_EXT_private_data v1
> 		VK_EXT_robustness2 v1
> 		VK_EXT_sample_locations v1
> 		VK_EXT_scalar_block_layout v1
> 		VK_EXT_separate_stencil_usage v1
> 		VK_EXT_shader_stencil_export v1
> 		VK_EXT_shader_viewport_index_layer v1
> 		VK_EXT_subgroup_size_control v2
> 		VK_EXT_swapchain_colorspace v4
> 		VK_EXT_texel_buffer_alignment v1
> 		VK_EXT_texture_compression_astc_hdr v1
> 		VK_EXT_vertex_attribute_divisor v3
> 		VK_AMD_gpu_shader_half_float v2
> 		VK_AMD_negative_viewport_height v1
> 		VK_AMD_shader_image_load_store_lod v1
> 		VK_AMD_shader_trinary_minmax v1
> 		VK_IMG_format_pvrtc v1
> 		VK_INTEL_shader_integer_functions2 v1
> 		VK_GOOGLE_display_timing v1
> 		VK_MVK_macos_surface v3
> 		VK_MVK_moltenvk v35
> 		VK_NV_fragment_shader_barycentric v1
> 		VK_NV_glsl_shader v1
> [mvk-info] GPU device:
> 		model: Apple M1
> 		type: Integrated
> 		vendorID: 0x106b
> 		deviceID: 0xd0003ef
> 		pipelineCacheUUID: 0000277F-0D00-03EF-0000-000000000000
> 	supports the following Metal Versions, GPU's and Feature Sets:
> 		Metal Shading Language 2.4
> 		GPU Family Apple 7
> 		GPU Family Apple 6
> 		GPU Family Apple 5
> 		GPU Family Apple 4
> 		GPU Family Apple 3
> 		GPU Family Apple 2
> 		GPU Family Apple 1
> 		GPU Family Mac 2
> 		GPU Family Mac 1
> 		GPU Family Common 3
> 		GPU Family Common 2
> 		GPU Family Common 1
> 		macOS GPU Family 2 v1
> 		macOS GPU Family 1 v4
> 		macOS GPU Family 1 v3
> 		macOS GPU Family 1 v2
> 		macOS GPU Family 1 v1
> [mvk-info] Created VkInstance for Vulkan version 1.1.224, as requested by app, with the following 3 Vulkan extensions enabled:
> 		VK_KHR_surface v25
> 		VK_EXT_debug_utils v2
> 		VK_EXT_metal_surface v1
> [mvk-info] Using emulation for Vulkan semaphores.
> [mvk-info] Created VkDevice to run on GPU Apple M1 with the following 3 Vulkan extensions enabled:
> 		VK_KHR_driver_properties v1
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_swapchain v70
> [mvk-info] Created 3 swapchain images with initial size (1280, 720) and contents scale 1.0 for screen Built-in Retina Display.
> [mvk-info] Created 3 swapchain images with initial size (1280, 720) and contents scale 1.0 for screen Built-in Retina Display.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: vkCmdCopyBufferToImage(): The image is using Metal format MTLPixelFormatInvalid as a substitute for Vulkan format VK_FORMAT_R5G6B5_UNORM_PACK16. Since the pixel size is different, content for the image cannot be copied to or from a buffer.
> [mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.
> libc++abi: terminating with uncaught exception of type std::runtime_error: failed to submit command buffer. Error -11
> zsh: abort      /Users/nalyahmad/Documents/Games/Wii\ U/Cemu\ Emulator/Cemu
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

This error caught my eye : 

> VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R5G6B5_UNORM_PACK16 is not supported on this device.

I think the issue is to do with macOS 13 or maybe the fact molten-vk hasn't been installed for macOS 13 but for 12 instead.

**Comment by Tillsunset** [comment] 2022-09-25 16:23
This is a known issue, duplicate of #290. It involves metal feature support of the gpu and molten-Vk incorrectly thinking this gpu doesn’t support this pixel format.

**Closed** 2022-09-26 06:37 UTC

**Comment by elisezhu123** [comment] 2022-10-12 06:35
the first step I was successfully but when I decided to download molten-vk it failed. 
 
showing no available formula with the name molten-vk
<img width="682" alt="截屏2022-10-11 下午11 35 07" src="https://user-images.githubusercontent.com/68165050/195267630-dd4d7f9d-20c1-4038-b82a-b8ab9bbad2bd.png">
<img width="682" alt="截屏2022-10-11 下午11 35 17" src="https://user-images.githubusercontent.com/68165050/195267655-1fc195e2-d073-4d27-b787-233dea2ed85b.png">

**Comment by Tillsunset** [comment] 2022-10-12 06:47
Try “ibrew doctor”. It will output some warnings/errors and the commands to fix them, that may solve your problem. In the future, please go to troubleshooting in the cemu discord.
