### ISSUE TITLE
Cemu freezes on opening with every title

### ISSUE THREAD

**Issue by eyedoc66** [cemu-project/Cemu#1212] opened 2024-05-21 03:06 UTC
### Current Behavior

Using a mini PC with i5 CPU, onboard HD graphics, and 8gigs ram.
Vulkan isn't supported. Using Opengl the games load, then I get immediately a diagonal split screen that stays with half the image inverted. But the audio is still running in the background. I've tried everything I can think of.

### Expected Behavior

Game to run

### Steps to Reproduce

Starting any title through Batocera V39, cemu 2.0

### System Info (Optional)

OS: linux
GPU:  on board HD 500 or 600

**Comment by Squall-Leonhart** [comment] 2024-05-21 03:59
>  GPU: on board HD 500 or 600

You need to figure this out,  both have vulkan on linux but the 600 is in a better spot support wise than the 500.

**Comment by Squall-Leonhart** [comment] 2024-05-21 04:00
If its the 500, it would be a duplicate of https://github.com/cemu-project/Cemu/issues/675

**Comment by eyedoc66** [comment] 2024-05-21 13:45
I'll double check, but I get a completely different error message.
I get a can't initialize -8 error.
This screen issue is when I try to use Opengl.

**Comment by Exzap** [comment] 2024-07-06 03:43
Closing this since it's stale and more of a troubleshooting request anyway which should be posted on our discord or subreddit

**Closed by Exzap** 2024-07-06 03:43 UTC
Labels: bug
