### ISSUE TITLE
[Feature Request] Make Alt+F4 close the Emulator

### ISSUE THREAD

**Issue by lunatic-gh** [cemu-project/Cemu#886] opened 2023-06-30 18:53 UTC
So, in previous versions of Cemu (everything before the 2.0 Release) had alt+f4 work perfectly fine, closing the app as expected.
But now in 2, it does exactly... nothing ._.

I've read in other issues its supposed to be an issue on Steam Decks only, but i'm not using a Steamdeck, nor am i using Linux in any form (alltho its the same behavior on my arch machine).

I don't think it matters, but for completion i'll put my full System specs below:

Windows 11 Pro
AMD Ryzen 7 5800X3D
AMD Radeon RX 6900XT
16GB DDR4 RAM
Latest Cemu version (2.0-42)

**Comment by chloecdn** [comment] 2023-06-30 18:55
maybe i should add: this only appears when in a game. when just opening the emulator itself, i can close it with alt+f4 perfectly fine.

**Comment by aem111607** [comment] 2023-06-30 21:01
Not really a feature request as much as a bug

**Comment by Squall-Leonhart** [comment] 2023-07-01 02:39
the context for the window accelerators are broken in some cases when the emulator transitions to running a game from the library list, this is already known but it requires some time and effort to figure out how and why, this will likely get looked at in the future when the rest of the DPI scaling is also looked at.

**Comment by chloecdn** [comment] 2023-07-02 19:30
This is weird, because even if Cemu is ran with a specific game via arguments (Cemu.exe -f -g "path/to/game"), it will still refuse to close, the same way as when opened from the game library. But maybe it's because of how the emulator behaves when opening games from arguments, i don't know.

**Comment by jonbarrow** [comment] 2023-07-24 05:30
Have you tried a more recent release? I'm on Ubuntu 22.04 and alt+F4 closes the emulator for me just fine, even in games

**Comment by chloecdn** [comment] 2023-07-28 04:29
> Have you tried a more recent release? I'm on Ubuntu 22.04 and alt+F4 closes the emulator for me just fine, even in games

Yes, i'm always on the latest version, right now on 2.0-45, and pressing alt+f4 does nothing when ingame. I'd take a wild guess and say it's a windows-only issue? Or maybe even Windows11-Only?

**Comment by spudpiggy** [comment] 2023-08-19 11:27
I'm on Windows 10 running 2.0-47 and I can't alt+f4 either.
Alt+Space then C is a lesser known way to close a window, and I can confirm that it works for me. There's a workaround, although I know it isnt ideal cus muscle memory.

**Comment by biblicabeebli** [comment] 2023-10-23 06:18
Summary/Update

Bug still present in 2.0-59.
Bug appears to be Wandows only.
Bug occurs only when a game is being actively emulated.
Bug appears to occur regardless of method used to launch game.

**Comment by spudpiggy** [comment] 2023-10-25 12:03
> Summary/Update
> 
> Bug still present in 2.0-59. Bug appears to be Wandows only. Bug occurs only when a game is being actively emulated. Bug appears to occur regardless of method used to launch game.

Thanks for reminding me to switch to Wandows! /j
I just checked, bug's still there. on 2.0-59
<unrelated>also, the Mii renderer bugged out and I saw this
![image](https://github.com/cemu-project/Cemu/assets/87132635/3f8730b8-a696-48f8-8bc7-0cbc019a6a13)
</unrelated>

**Comment by biblicabeebli** [comment] 2023-10-25 13:17
I never Jest.
![image](https://github.com/cemu-project/Cemu/assets/1715982/d602fc23-f2df-43e9-ae84-281404abc8b9)

**Comment by HobbyloserMensch** [comment] 2024-01-07 10:06
This bug exists since i don't know anymore it looks like it will never be solved.

**Comment by kianagit** [comment] 2024-01-08 20:35
> This bug exists since i don't know anymore it looks like it will never be solved.

This aged like fine milk ahahaha, but finally a fix was found. Gonna wait with closing this until it's actually merged.

**Closed** 2024-09-25 14:51 UTC
