### ISSUE TITLE
[Feature Request] and  Settings/Input Window issues

### ISSUE THREAD

**Issue by MetallicaPixel** [cemu-project/Cemu#815] opened 2023-05-11 15:04 UTC
Can CEMU go back to the game list window  instead of just quitting when you close window of a running game?  On Mac,  if I close the window of a game thats running its quits CEMU and I have to relaunch it. 

Also as of 2.0-39  I can't open the general  settings or input settings window when a game is running and as the above issue I can't go into those windows to change things unless I quit the app or close the game window, which quits CEMU, then relaunch. 

Mac OS 13.3.1
4.2 GHz Quad-Core Intel Core i7

**Comment by Exzap** [comment] 2023-05-11 15:28
There is no "back to game list" for a bunch of technical reasons. It's planned tho.

> can't open the general settings or input settings window when a game is running

I'm not sure what you mean by that. The general settings and input settings should always be available. You just need to quit out of fullscreen mode with Escape or F11 key. Not all settings can be changed while a game is running obviously, but you should be able to at least access the option windows at any time.

Anyway, this is a duplicate of #219

**Closed by Exzap** 2023-05-11 15:28 UTC
