### ISSUE TITLE
[Feature Request] FSR upscaling

### ISSUE THREAD

**Issue by hvcrios** [cemu-project/Cemu#976] opened 2023-09-23 14:28 UTC
If it is at all possible of course

Would give those with weaker hardware a way to have everything looking prettier without losing too much performance, when running at a lower resolution.

**Comment by Exzap** [comment] 2023-09-23 14:33
Duplicate of #770
If someone wants to add this they are free to do so, but as far as I know none of the current contributors are interested. It may still happen at some point.

**Closed by Exzap** 2023-09-23 14:33 UTC
