### ISSUE TITLE
Sonic & All Stars Racing Transformed - Starry Speedway Crash

### ISSUE THREAD

**Issue by yasmindevan** [cemu-project/Cemu#1207] opened 2024-05-19 02:07 UTC
### Current Behavior

The game automatically quits when I try to load the Starry Speedway level in World Tour, no matter what setting I try. Can't skip it and continue to other levels, so that's a bummer that i'm stuck here. 

### Expected Behavior

Load like normal

### Steps to Reproduce

Just play the Starry Speedway level, it will automatically quit. 

### System Info (Optional)

OS: Mac
GPU: M1

### Logs (Optional)

[log.txt](https://github.com/cemu-project/Cemu/files/15367310/log.txt)

**Comment by Exzap** [comment] 2024-05-19 02:13
Duplicate of #1204

**Closed by Exzap** 2024-05-19 02:13 UTC
Labels: bug
