### ISSUE TITLE
Shaders making Cemu crashing (probably)

### ISSUE THREAD

**Issue by UsRnM44** [cemu-project/Cemu#967] opened 2023-09-13 20:56 UTC
While running game on the Cemu, while starting to loading the game, the entire Cemu makes crash. Removing shader cache makes the game playable again.
I don't know how to reproduce it, since it's occurring only in one game so far (Breath of the Wild). While it's not makes the game unplayable, it's making shaders shuttering.

Does occurring with and without modes.

(dunno if it's important, but it's occurring on Mac, Intel CPU, AMD GPU, 16gb memory)

https://github.com/cemu-project/Cemu/assets/122369709/eaae2eeb-6c61-4989-b0c6-f280ddf4b35b

**Comment by Exzap** [comment] 2023-09-13 20:59
Duplicate of #396

**Closed by Exzap** 2023-09-13 20:59 UTC
