### ISSUE TITLE
[macOS] Unrecoverable error in Vulkan renderer

### ISSUE THREAD

**Issue by GreyAsteroid** [cemu-project/Cemu#491] opened 2022-11-13 17:40 UTC
Cemu 2.0-15 (experimental)
molten-vk 1.2.0 (brew)
2017 iMac (iMac18,3)

Crashes when trying to load a game.

log.txt
```
[12:30:05.320] ------- Init Cemu 2.0-15 (experimental) -------
[12:30:05.320] Init Wii U memory space (base: 0x000000010e422000)
[12:30:05.320] mlc01 path: /Users/eric/Documents/My Games/Cemu/mlc01
[12:30:05.320] Used CPU extensions: SSSE3, SSE4.1, AVX2, AES-NI
[12:30:05.320] IOSU_CRYPTO: No otp.bin found. Online mode cannot be used
[12:30:05.320] IOSU_CRYPTO: No Seeprom.bin found. Online mode cannot be used
[12:30:05.333] Failed to read valid PlayDiary header
[12:30:06.539] Mounting title 00050000101c9400
[12:30:06.539] Base: /Users/eric/Documents/My Games/Cemu/mlc01/usr/title/00050000/101c9400 [Folder]
[12:30:06.539] Update: /Users/eric/Documents/My Games/Cemu/Games/Updates and DLC/The Legend of Zelda Breath of the Wild (UPDATE DATA) (v208) (3.243 GB) (USA) (unpacked) [Folder]
[12:30:06.539] DLC: /Users/eric/Documents/My Games/Cemu/Games/Updates and DLC/The Legend of Zelda Breath of the Wild (DLC) (2.182 GB) (USA) (unpacked) [Folder]
[12:30:07.100] COS: System fonts found. Generated shareddata (26609KB)
[12:30:07.103] ------- Init Vulkan graphics backend -------
[12:30:07.103] Vulkan instance version: 1.2
[12:30:07.105] Using GPU: AMD Radeon RX 580
[12:30:07.105] Driver version: 1.2.0
[12:30:07.105] VK_EXT_custom_border_color not supported. Cannot emulate arbitrary border color
[12:30:07.105] VulkanLimits: UBAlignment 256 nonCoherentAtomSize 256
[12:30:07.105] Enable robust buffer access
[12:30:07.109] Using available debug function: vkCreateDebugUtilsMessengerEXT()
[12:30:07.109] Vulkan device memory info:
[12:30:07.109] Heap 0 - Size 8192MB Flags 0x00000001
[12:30:07.109] Heap 1 - Size 32768MB Flags 0x00000000
[12:30:07.109] Memory 0 - HeapIndex 0 Flags 0x00000001
[12:30:07.109] Memory 1 - HeapIndex 1 Flags 0x0000000e
[12:30:07.109] Memory 2 - HeapIndex 0 Flags 0x0000000b
[12:30:07.109] VK_FORMAT_R4G4B4A4_UNORM_PACK16 not supported
[12:30:07.109] VK_FORMAT_R4G4_UNORM_PACK8 not supported
[12:30:07.109] VK_FORMAT_R5G6B5_UNORM_PACK16 not supported
[12:30:07.109] VK_FORMAT_R5G5B5A1_UNORM_PACK16 not supported
[12:30:07.773] ------- Loaded title -------
[12:30:07.773] TitleId: 00050000-101c9400
[12:30:07.773] TitleVersion: v208
[12:30:07.773] TitleRegion: US
[12:30:07.773] Save path:   /Users/eric/Documents/My Games/Cemu/mlc01/usr/save/00050000/101C9400/user/
[12:30:07.773] Shader cache file: shaderCache/transferable/00050000101c9400.bin
[12:30:07.773] gameprofile path: gameProfiles/00050000101c9400.ini
[12:30:07.773] RPX hash (updated): fb7911ad
[12:30:07.773] RPX hash (base): dcac9927
[12:30:07.900] Loaded module 'u-king' with checksum 0x6267bfd0
[12:30:07.900] RPL link time: 126ms
[12:30:08.048] HLE scan time: 148ms
[12:30:08.048] ------- Active settings -------
[12:30:08.048] CPU-Mode: Multi-core recompiler (gameprofile)
[12:30:08.048] Load shared libraries: true (gameprofile)
[12:30:08.048] Use precompiled shaders: auto (gameprofile)
[12:30:08.048] Full sync at GX2DrawDone: true
[12:30:08.048] Async compile: false
[12:30:08.048] Console language: English
[12:30:09.185] Unrecoverable error in Vulkan renderer
[12:30:09.185] Msg: Failed to create pipeline cache: -3
```

**Comment by Squall-Leonhart** [comment] 2022-11-13 17:42
Duplicate of https://github.com/cemu-project/Cemu/issues/396

**Comment by GreyAsteroid** [comment] 2022-11-13 17:49
> Duplicate of #396

I was looking at both that and https://github.com/cemu-project/Cemu/issues/406 but both mention being able to delete ShaderCache to workaround them while that does not make a difference in this case.

**Closed** 2022-11-13 17:49 UTC
