### ISSUE TITLE
I hope to add more functionality options within the Cemu emulator

### ISSUE THREAD

**Issue by 123shuhai** [cemu-project/Cemu#1231] opened 2024-06-09 11:51 UTC
### Your suggestion

I also wonder why, with the current updates to the Cemu emulator, additional functionalities cannot be incorporated. During gameplay, there is no option to pause, restart, or exit the game; one can only exit and close the emulator entirely. This limitation detracts significantly from the user experience.

**Comment by Exzap** [comment] 2024-06-09 13:46
Duplicate of #219

**Closed by Exzap** 2024-06-09 13:46 UTC
Labels: feature request
