### ISSUE TITLE
[Linux] [appimage] 2.0.16 "segmentation fault! error signal 11"

### ISSUE THREAD

**Issue by angelrcd** [cemu-project/Cemu#513] opened 2022-11-19 14:22 UTC
Cemu crashes when I try to run a game or enter the general settings, all the other options seem to work fine (controller settings, graphic packs, etc...)
The terminal log shows this message: 
![image](https://user-images.githubusercontent.com/114014506/202855464-f8a9c3df-18c5-47a7-afca-8bf338d8fbb8.png)

**Comment by qurious-pixel** [comment] 2022-11-19 17:54
Try running in OpenGL.
Or disable paranoid mode as the message states
`sudo sysctl -w dev.i915.perf_stream_paranoid=0`

**Comment by j5155** [comment] 2022-11-22 21:16
I also get this error on the latest github actions appimage and on 2.0-17.
On Ubuntu 22.04, running BOTW and riding a horse north of dueling peaks stable.
Log:
`/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_tls_channel_binding_error_quark
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
Gtk-Message: 12:09:54.347: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:09:54.349: Failed to load module "canberra-gtk-module"

(AppRun.wrapped:885077): Gtk-CRITICAL **: 12:09:54.666: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
MESA: error: failed to load D3D12
../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Segmentation fault!
Error: signal 11:
/tmp/.mount_Cemu-ciKEMik/AppRun.wrapped() [0x8754bf]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fe34b7bd520]
[0x7fe0e379e2ad]+[0x7fe0e379e2ad]
`

**Comment by qurious-pixel** [comment] 2022-11-25 18:17
@j5155 if you are running WSL or in a VM, you have to install `d3d12_dri.so`

WSL you may have to update your kernel with `WSL --update`

In a VM, You may have to install the appropriate MESA ppa to update your graphics

**Comment by j5155** [comment] 2022-11-25 19:04
I'm not running in a VM or under WSL, but if you have specific installation instructions I would be fine with trying that.

**Comment by arijnr** [comment] 2022-12-31 08:08
I think this issue is a duplicate of https://github.com/cemu-project/Cemu/issues/466

To play with OpenGL, open the file settings.xml, and search for this part:
```
    <Graphic>
        <api>1</api>
```
Then, change the 1 to 0:
```
    <Graphic>
        <api>0</api>
```

Save the file, and reopen Cemu. You will be able to play with OpenGL now.
If you go to settings and try to set Vulkan, the error will happen again.

**Closed** 2024-07-27 01:31 UTC
