### ISSUE TITLE
Enter a title for the bug report here

### ISSUE THREAD

**Issue by Julinkk** [cemu-project/Cemu#1346] opened 2024-09-17 12:58 UTC
### Current Behavior

Hello, I am trying to understand and solve a problem that I have had for several months with cemu, I have a significant input lag whereas with the old versions I had no problems, I tried starting from a clean installation with exactly the same settings and on cemu 2.0.36 I have no problems whereas with all the latest versions of cemu for a while the input lag is much more significant, impossible to find where the problem comes from

I just tested several versions to see from which moment the problem appears and it is with version 2.0-77, no input lag problem with version 2.0-75 and all those before

### Expected Behavior

low input lag

### Steps to Reproduce

all versions from version 2.0-77 to version 2.1

### System Info (Optional)

OS: windows
GPU: 1060 6gb

**Comment by goeiecool9999** [comment] 2024-09-17 14:01
This is a duplicate of #1239. We merged a PR to address the problem yesterday. Look out for it with the next experimental release. In the mean time, try setting vsync to triple buffered or disabled.

**Closed by goeiecool9999** 2024-09-17 14:01 UTC
Labels: bug
