### ISSUE TITLE
[Feature Request] Option to select the default audio device

### ISSUE THREAD

**Issue by italoghost** [cemu-project/Cemu#1016] opened 2023-11-03 17:36 UTC
Hi! I usually play on my TV, launching the games through Steam Big Picture mode. While doing that, the default audio changes to the TV, instead of my headphone. 

The problem is that Cemu only has the option to select a specific device and the audio still continues to play on my headphone.

The ability to select the default audio device would be very nice!

**Comment by Squall-Leonhart** [comment] 2023-11-03 19:25
Duplicate of [#](https://github.com/cemu-project/Cemu/issues/29)

**Comment by aws0** [comment] 2023-11-07 16:18
@italoghost I have same issue, I endded up creating simple script (it's a hack) runs in steam launch options before calling Cemu (Iuse the flatpak version)
The script plays a simple file and detects current default audio channel (reported by Linux) , then it updates the Cemu config file, link to script here (see comments on how to use it): https://github.com/aws0/beast-notes/blob/main/steamdeck-cemu-audio/audio-sink-cemu.sh

I hope it helps

**Comment by specterflare** [comment] 2024-03-01 04:13
Shouldn't #1017 have closed this?

**Comment by Exzap** [comment] 2024-03-06 18:06
Yes, this is fixed by #1017

**Closed by Exzap** 2024-03-06 18:06 UTC
