### ISSUE TITLE
[Feature Request] convert to .WUA format in bulk

### ISSUE THREAD

**Issue by mx00010** [cemu-project/Cemu#712] opened 2023-03-26 04:40 UTC
Currently, the convertion only work be selecting one title at the time (since version 1.27 who added the .WUA format support). This can be convinient to add a way to select multiple titles in the title manager window to create and start a queue of titles to be converted in .WUA format.

**Comment by Exzap** [comment] 2023-03-26 11:29
Duplicate of #35

**Closed by Exzap** 2023-03-26 11:29 UTC
