### ISSUE TITLE
Skylanders Portal is not being recognized by Cemu on Mac.

### ISSUE THREAD

**Issue by SpyroPortal** [cemu-project/Cemu#1081] opened 2024-01-24 12:06 UTC
### Current Behavior

Skylanders Portal is not being recognized by cemu on Mac.

### Expected Behavior

I have been trying for several days now to play skylanders on Mac, all games launch, but once I get to the “connect portal” screen, nothing happens even though a Wii U portal is connected to my Mac, and I can see it as “Spyro Portal” in my devices.

I did some digging and found that even people on Windows are downgrading to version 2.0-47 to fix a portal-related issue there, so I tried that version on Mac and also nothing happened.

A friend of mine told me that maybe you need to install libusb on Mac using Homebrew in order for Cemu to read the portal, and even with installing libusb, Cemu was still unable to detect the portal.

What is the fix to this? How are you guys being able to play the Skylanders games on Mac?

### Steps to Reproduce

Connecting the portal to Mac, then starting the app.

### System Info (Optional)

OS: 
GPU:

**Comment by JaimieVandenbergh** [comment] 2024-01-24 12:07
The windows 2.0-47 is from before the new USB work-in-progress that'll help Portals work on Mac, because it's in progress and incomplete.
Once it's finished the intent is that portals will work on Mac. You'll just have to wait until that's done.

**Comment by SpyroPortal** [comment] 2024-01-24 12:10
> The windows 2.0-47 is from before the new USB work-in-progress that'll help Portals work on Mac, because it's in progress and incomplete. Once it's finished the intent is that portals will work on Mac. You'll just have to wait until that's done.

I also tried the latest version 2.0-65 on Mac, and still the portal was not detected.
So there is no release availble on Mac right now that can read the portal?!

**Comment by Exzap** [comment] 2024-01-24 12:24
> So there is no release availble on Mac right now that can read the portal?!

Correct. One of the reasons why its being reworked is to add Linux and Mac support.
Closing this since it's technically not a bug.

**Closed by Exzap** 2024-01-24 12:24 UTC
Labels: bug

**Comment by SpyroPortal** [comment] 2024-01-24 12:26
> > So there is no release availble on Mac right now that can read the portal?!
> 
> Correct. One of the reasons why its being reworked is to add Linux and Mac support. Closing this since it's technically not a bug.

But does this mean that once the new update is out portals will work on Mac without having to Homebrew and use Libusb? Or i still must do it? Please tell me.

**Comment by Exzap** [comment] 2024-01-24 13:31
Once ready it should work out of the box without the need to install anything extra

**Comment by SpyroPortal** [comment] 2024-01-24 16:39
> Once ready it should work out of the box without the need to install anything extra

Thank you so so much for letting me know, I have been struggling for the past two days in order to find a solution for the issue, now I know I can rest and just wait..

Is there an expected time-frame of when might the update release? or if it is gonna be the next upcoming update or the release has to wait for more than that? 
Thanks again.
