### ISSUE TITLE
[Feature Request] Option to pause, resume and end emulation?

### ISSUE THREAD

**Issue by ghost** [cemu-project/Cemu#219] opened 2022-09-09 13:19 UTC

**Comment by jamie01** [comment] 2022-09-24 15:01
This would be a welcome addition, particularly in light of how badly the Steam Deck handles suspend/resume for many emulators, Cemu included. Being able to pause emulation (and possibly dump/reload state) would be immensely helpful.

**Comment by Skyrimer3d** [comment] 2022-10-13 21:14
Agree on this issue, this would help Steam Deck usability inmensely since right now it freezes after resume, which makes CEMU not too useful for a portable device.
 This issue ocurred on other emus too, this may help to fix it:
https://github.com/yuzu-emu/yuzu/issues/8194
https://github.com/RPCS3/rpcs3/issues/12123

**Comment by Amnesia1000** [comment] 2022-10-29 12:47
Pause, resume and stop emulation. Having to close Cemu to be able to play another game is annoying.

**Comment by Exzap** [comment] 2024-07-06 03:41
I just noticed that op deleted their account and due to that the text of the issue is also gone. Furthermore I don't think we really need to track something as obvious as the ability to stop/pause games. It's mostly dependent on some larger refactoring but the work is underway, albeit very slow. For these reasons I will be closing this issue

**Closed by Exzap** 2024-07-06 03:41 UTC

**Comment by yunylz** [comment] 2025-01-18 23:17
any updates?

**Comment by joex92** [comment] 2025-08-04 02:47
any updates?

**Comment by paidlowered** [comment] 2026-01-19 05:11
Want either this or a snapshot feature
