### ISSUE TITLE
Cemu2.0-19 Twilight Princess HD map bug

### ISSUE THREAD

**Issue by Meggiej** [cemu-project/Cemu#569] opened 2022-12-10 10:18 UTC
For MacBook Pro
Macos 12.4
M1 core
Twilight Princess HD 
little map missing
<img width="1280" alt="截屏2022-12-10 18 14 29" src="https://user-images.githubusercontent.com/42362117/206849639-edb0fe99-30f2-4bdf-b7cc-58e24bc1794d.png">

**Comment by Exzap** [comment] 2022-12-10 10:38
We're currently waiting for MoltenVk to add geometry shaders. In the meantime I'm closing this since there is no point in having an open issue for every single game specific problem that is caused by lack of GS support.

**Closed by Exzap** 2022-12-10 10:38 UTC
