### ISSUE TITLE
Broken speaker texture on Splatoon Plaza when changing scenes + Certain broken splat-button textures

### ISSUE THREAD

**Issue by AlphaCraft9658** [cemu-project/Cemu#944] opened 2023-08-18 08:30 UTC
I have noticed, that when I change back to the plaza from a different scene and get close to the speakers, the overlayed texture glitches out and even disappears. Additionally, some of the splat-type buttons, especially in campaign, have this glitched border. I do use the community graphics pack and 60FPS on plaza, but the same issues occour without these enabled. So this seems to be an issue with Cemu. I also have this video for demonstration:
https://drive.google.com/file/d/1lcQPQqdmGDUJ9PWXX1IMZtS8lQNAohC1/view?usp=drive_link

**Comment by Exzap** [comment] 2023-08-18 10:25
The video isn't accessible. In general try to avoid linking external videos. You can upload screenshots and small videos directly to github. Also please attach log.txt

**Comment by AlphaCraft9658** [comment] 2023-08-18 11:01
> The video isn't accessible. In general try to avoid linking external videos. You can upload screenshots and small videos directly to github. Also please attach log.txt

I know I can, but the file was too large. I have fixed the permissions now. Forgot to change them earlier.

**Comment by AlphaCraft9658** [comment] 2024-03-15 20:44
> The video isn't accessible. In general try to avoid linking external videos. You can upload screenshots and small videos directly to github. Also please attach log.txt

Anything new regarding this issue? As I mentioned, the permissions are fixed and you should be able to see the footage. I am going to avoid external links in the future, as far as possible.

**Comment by Exzap** [comment] 2024-03-16 03:37
No news on this. The cause of the lighting problem is generally understood, but a good solution still has to be found. The pixel glitches in the UI are a little easier to fix but I just haven't found the time to do it yet.

I noticed this is a partial duplicate of #207 so I am going to close this. The other issue doesn't mention the UI bug but I dont think it needs explicit tracking since it's pretty obvious and a well known issue with Splatoon

**Closed by Exzap** 2024-03-16 03:37 UTC
