### ISSUE TITLE
[Bug] [Linux/Flatpak] Crashing when starting a game in OpenGL

### ISSUE THREAD

**Issue by Meepster-836** [cemu-project/Cemu#1043] opened 2023-12-15 00:45 UTC
Specifically on the Flatpak version of Cemu (currently at 2.0-61), attempting to open a game with OpenGL set as the graphics API will immediately crash Cemu.

Using Pop!_OS 22.04, detailed system specs in the log:
[log.txt](https://github.com/cemu-project/Cemu/files/13679616/log.txt)

Using OpenGL seems to work on the AppImage version of Cemu. (though it has it's own problems with XCX, but that may not be relevant.)

**Comment by Squall-Leonhart** [comment] 2023-12-15 00:55
Duplicate of https://github.com/cemu-project/Cemu/issues/993

**Comment by Meepster-836** [comment] 2023-12-15 01:02
Ah, I'm sorry I didn't notice.

**Closed** 2023-12-15 01:02 UTC
