### ISSUE TITLE
Various Bugs with Breath of the Wild as of updating to 2.0-86 (Appimage)

### ISSUE THREAD

**Issue by CreeperofDoom** [cemu-project/Cemu#1235] opened 2024-06-15 14:24 UTC
### Current Behavior

Various bugs with Breath of the Wild occur ever since i updated to the Cemu 2.0-86 Appimage on Linux
Bugs Include:
Infinite Loading when in the Overworld, Entity Sounds (Guardian, Korok, Bokoblin or Hinox) Sounds play loudly despite not being close to any of those, Object Flickering and Random Crashing. None of these occured on previous Cemu Versions. Using my exact Graphics Packs and Settings as before. No BCML Mods are installed

### Expected Behavior

None of the listed bugs. Which did not occur in prior versions

### Steps to Reproduce

Using the Cemu 2.0-86 Appimage
Graphics Packs Used:
Draw Distance, Extended Memory, FPS++, Grass Swaying (Vulkan), Enhancements and Graphics

### System Info (Optional)

OS: Arch Linux
GPU: RTX 3070

**Comment by Exzap** [comment] 2024-06-15 15:24
Please attach log.txt so we can see the exact configuration. Also please say which version you are comparing to (and post a log for that too, ideally)

At any rate, most of this does sound like known graphic pack problems. The weather pack has a glitch where it can mess with the loudness of some sound effects. I also heard reports of a similar issue when Cemu's audio output is set to surround, in which case setting it to Stereo should fix it.

Infinite loading can have lots of causes, at the minimum it can be caused by setting the framerate too high with FPS++. Flickering and crashing is a common symptom of draw distance (again by setting it too high, but crashes can rarely occur even with lower settings)

**Comment by CreeperofDoom** [comment] 2024-06-16 13:04
[log.txt](https://github.com/user-attachments/files/15858067/log.txt)

**Comment by CreeperofDoom** [comment] 2024-06-16 21:23
There seems to be MORE Problems too: The game slows down Randomly, its not frame drops because Cemu and my Other FPS Overlay reports no drops, and that it still feels smooth while being laggy. Some In-Game Enemies refuse to attack me, The Combat Theme still plays. Some Audio feels buffered and delayed and Sometimes the game Autosaves Forever resulting in a Corrupted Autosave. Again no BCML mods and this didn't happen on previous Cemu versions

**Comment by Exzap** [comment] 2024-06-17 10:22
Ok, so the problem when you list a bunch of issues like that is that it's unactionable from our side. Remember, this is a bug tracker for confirmed flaws in the software and not a general troubleshooting place. If you are looking for troubleshooting, I recommend visiting our Discord or subreddit.

I will close this issue since in my eyes it is too vague for a bug tracker, but for future reference how to properly raise a bug:

- Be as precise as possible. For example, "It worked in previous Cemu versions" is too vague to be useable information for us. Which version did it last work with?
- Narrow the problem down as much as you can. By for example turning graphic packs off one-by-one and seeing if the problem goes away.
- Provide clear steps to reproduce and a clear explanation of the problem ("its laggy" can mean many different things)
- Mass reporting in generally is just messy and it's better to look at one problem at a time. That means for bug reporting, you'd open one issue per problem

Thank you for your understanding

**Closed by Exzap** 2024-06-17 10:22 UTC
Labels: bug
