### ISSUE TITLE
Feature Request: Full wiimote support for Linux

### ISSUE THREAD

**Issue by GNUGradyn** [cemu-project/Cemu#885] opened 2023-06-30 16:39 UTC
Hello. I am trying to play super mario bros U on my steam deck with real wiimotes. I've run into a show-stopper roadblock. You can get this *mostly* working by adding the wiimotes via the SDLController API and mapping the buttons properly. This has been the solution for wiimotes in CEMU on linux. However, SDLController understandably does not map the accelerometer, so any games requiring the accelerometer (most wiimote games) will not work. 

On windows this is not a problem, because you can forward the wiimote directly into CEMU to get full support
![image](https://github.com/cemu-project/Cemu/assets/20762604/8548ebeb-890e-4238-bf2a-32b1a635346e)

Running CEMU in proton also does not solve the problem, because proton does not forward the wiimotes to the emulator. I'm hoping the "Wiimote API" functionality could be brought to linux so wiimote games can be fully playable

**Comment by kevincrans** [comment] 2023-07-04 20:50
Is this a possible duplicate of #472 ?
I submitted an issue where that was a duplicate of.

**Comment by GNUGradyn** [comment] 2023-07-04 21:01
Not really. #472 is a different issue, and while SDLController not really being sufficient is the root cause in both cases, the solution they are chasing is very different from what I am proposing with this feature request. The issues linked in #472 propose updating SDLController for better button mapping (which seems to already be done at least on experimental). That addresses the button mapping issue but leaves accelerometer/gyro/pointer controls out. What we need to allow these controls to work and ultimately attack this issue at its core is full native wiimote support on Linux like windows has.

**Comment by GNUGradyn** [comment] 2023-08-28 21:44
Noticed this was added. Massive thanks to the team I'll be donating

**Closed** 2023-08-28 21:49 UTC
