### ISSUE TITLE
BotW getting stuck at the start [MacOS]

### ISSUE THREAD

**Issue by UsRnM44** [cemu-project/Cemu#965] opened 2023-09-10 20:58 UTC
Using MacOS, Intel with AMD processor 16GB memory, I installed the game with it's latest patch and DLC. Using the latest build 2.0-48.
As I'm usually doing, I'm checking the game for the first time to see if it's emulating correctly, and also for the sake of shader building, I played the game 'till the point of the first shrine.
However, upon my 2nd time playing, to officially start the game, it got stuck right when activating the first tower. The FPS is dramatically dropping and the game stuck while hearing the sound for the tower activating. But even after all that, the game kept when it got stuck.

(screenshot for when the game got stuck)
<img width="1280" alt="Screenshot 2023-09-10 at 23 47 26" src="https://github.com/cemu-project/Cemu/assets/122369709/c65aac1c-b889-4f23-9fd9-75e5fc8f17fc">

**Comment by Squall-Leonhart** [comment] 2023-09-10 21:13
only two instances of shrine issues to my recollection.

2.0 original release
bad game files.

**Comment by UsRnM44** [comment] 2023-09-10 21:23
What is Hackintosh?
The game is dumped to ISO.
<img width="750" alt="Screenshot 2023-09-11 at 0 21 54" src="https://github.com/cemu-project/Cemu/assets/122369709/769dc756-5d4b-480d-81d6-48eeeeac9208">

All my dumped WiiU are like this 
(though I don't have much, Wind Waker HD and Xenoblade Chronicles X)

**Comment by Squall-Leonhart** [comment] 2023-09-10 22:17
This dump is either 

- from an old tool and might have been dumped badly, 

- or its not your own copy and you used an illegal tool that is not permitted to be discussed, or supported.

**Comment by UsRnM44** [comment] 2023-09-10 22:52
I don't understand why you judging this bug as for the dumping quality. As I said, it had been worked in my first play, why not to think that something else causing it?

The closest I think might be the cause, is this:
https://github.com/cemu-project/Cemu/issues/217

**Comment by Squall-Leonhart** [comment] 2023-09-10 23:10
It does, but the shrines popping up is not one of them.

**Comment by UsRnM44** [comment] 2023-09-10 23:17
I get your point, but if it were bad dump issue, how come the scene went flawlessly in my first try? (with FPS++ and Graphic modes and all)
And I'm saying that because I did tried to dump the game again, properly. (In my original edit I wrote a lot about couple of things I tried, including deleting Cemu and such, with not vail. But in the end it seems more appropriate for tech support than bug, so I removed it)

**Comment by Squall-Leonhart** [comment] 2023-09-10 23:23
Hold up, it looks like part of the scene is H264 so you might be right, the wide vista and distant shots aren't in engine.

**Comment by UsRnM44** [comment] 2023-09-10 23:44
When H264 API logging, the entire emulator crashing once starting a game, without even a crash log.

**Comment by UsRnM44** [comment] 2023-09-10 23:59
At first enabling the H264 API did fixed it, but the scene still didn't finished until then end before getting stuck. When tried this for another few tries, it got stuck like always.
I would say that my Mac just got old, but it runs smoothly Xenoblade Chronicles X, and Switch games at Ryujinx. So it doesn't seems like it lol

**Comment by Exzap** [comment] 2023-09-11 05:39
This is a duplicate of #217
As a workaround you can delete/rename the video files in the game's content folder and then it should just skip it instead of freezing.

**Closed by Exzap** 2023-09-11 05:39 UTC
