### ISSUE TITLE
I noticed this whenever it updates to the newest version

### ISSUE THREAD

**Issue by ramonava909** [cemu-project/Cemu#1423] opened 2024-11-22 08:27 UTC
### Current Behavior

Whenever Cemu updates to the newest version it has this error problem where it crashes the current version of the program instead of losing it out but the newest version opens up still. I don't know how to explain it but it happens a lot whenever it updates to the newest version of the program.

### Expected Behavior

The newest version of the program should open up instead of having the old version of the program crashing every time.

### Steps to Reproduce

i don't know how to fix this program

### System Info (Optional)

OS: 
GPU:

**Comment by Squall-Leonhart** [comment] 2024-11-22 08:33
duplicate of #424

**Closed** 2024-11-22 10:53 UTC
Labels: bug
