### ISSUE TITLE
[macOS] Have to delete shaderCache everytime for BOTW

### ISSUE THREAD

**Issue by Ventority** [cemu-project/Cemu#544] opened 2022-11-30 16:38 UTC
Hey, I just updated to v.2.0-19 from 2.0-16. Now I have to delete the shaderCache everytime I launch BOTW. I have to do that every time, independend of changing any settings or graphicpacks. MK8 for example works "flawless", at least, I dont have this issue. It worked before. Maybe I've overread something in the changelogs, then just close this issue. 
I'm on a base model M1 Pro 14' Macbook Pro, MoltenVK 1.2.0. 

log file:
[log.txt](https://github.com/cemu-project/Cemu/files/10125245/log.txt)

**Comment by qurious-pixel** [comment] 2022-11-30 16:46
duplicate of https://github.com/cemu-project/Cemu/issues/396

**Closed** 2022-11-30 17:11 UTC
