### ISSUE TITLE
Breath of the Wild - Crashes with pre-rendered Scenes?

### ISSUE THREAD

**Issue by MichaelW1980** [cemu-project/Cemu#27] opened 2022-08-24 20:39 UTC
**Version:** CEMU 2.0 - Windows Version.
**Hardware:** Core i5 8500, 32GB DDR4 3200, GTX 1660 ti (DCH Driver version 516.94)
**Game:** Breath of the Wild (Version 208, DLC 80)
**Log-File:** [log.txt](https://github.com/cemu-project/Cemu/files/9419118/log.txt)
**Settings:** It is a completely clean installation. All Default Settings. No Graphics Packs used.

I gave my 100% save state a go. All Blights have been taken care o before. The Moment, the Champion Scenes play, i get a black screen on the game for about 1-2 seconds. Then CEMU stops. No Error Message. It simply closes. I created a clean install for CEMU 1.27.1 to test, wether it worked there. Again, All default Settings. No Graphics Packs used. And yes, in 1.27.1 the scenes ran without a problem. 

With no graphics packs to create any problems and all default settings on both Versions, I can only assume, that CEMU 2.0 has an issue either all, or at least that particular prerendered cutscene. To make sure, if its just that one or any cutscene, I created an empty profile to start a game from scratch, left the Shrine of Ressurrection, ran to the Tower and started that Cutscene just the same. And again, CEMU 2.0 crashed, CEMU 1.27.1 didnt. It seems, Breath of the Wild crashes with any prerendered cutscene. Back to the 100% save state I played memories and hat the same crashes on CEMU v2.0, but no crashes in CEMU v1.27.1.

**Edit:** I didn't use any additional plugins or mods in CEMU.

**Comment by BParks21** [comment] 2022-08-24 21:06
I can confirm it doesn't seem to crash with 1.27.1 with or without cemuhook.

**Comment by WryOpussum** [comment] 2022-08-25 14:05
Can confirm this is a issue

**Comment by RomZerr0** [comment] 2022-08-29 18:12
Issue is in Cemuhook's hack where it always returns a small size for H264DECMemoryRequirement, can be fixed by bypassing this hack in H264Dec line 32. Cutscenes render when i return false to BoTW check. This isn't correct fix, but makes the game playable at least

**Comment by RomZerr0** [comment] 2022-08-29 18:17
Forked the project with temporary fix. 
https://github.com/RomZerr0/Cemu

**Comment by Darkhost1999** [comment] 2022-08-29 20:12
I'll wait for the PR. Although thanks for the information. I imagine a working fix can be utilized from this information.

**Comment by Zorklis** [comment] 2022-09-02 16:24
Impressive this hasn't been fixed day 1, let alone for a week

**Comment by Masamune3210** [comment] 2022-09-03 14:35
Lot of things going on right now, chill lol. It will get fixed when someone gets around to it, unless you want to do it yourself, your best choice is to wait patiently

**Comment by Squall-Leonhart** [comment] 2022-09-06 03:07
This is fixed in Experimental release 1.

**Comment by bitscher** [comment] 2022-09-06 04:45
Fixed by PR #174

**Comment by Zorklis** [comment] 2022-09-06 12:47
Can confirm no more crashes! Great job @lijunyu-cn

**Comment by Darkhost1999** [comment] 2022-09-06 12:58
I have a hard time believing that PR to be the only fix for this issue looking at it's change and it's comment.
Although, the issue is solved.

**Comment by Exzap** [comment] 2022-09-06 18:06
It was fixed by a2abffd37b9ce62d8d5d52031ec6c56a7fd03938 together with many other crashes

**Closed by Exzap** 2022-09-06 18:06 UTC
Labels: bug, regression
