### ISSUE TITLE
Pause the emulation and add a button to stop the emulation without the need to restart CEMU to switch games

### ISSUE THREAD

**Issue by wandpro** [cemu-project/Cemu#1251] opened 2024-07-05 11:38 UTC
### Your suggestion

I would like a button to allow me to pause the game emulation to be able to free up power on my PC (most emulators have a button to pause the emulation so it would be nice to add it in CEMU).

And I would like a button to be able to stop the emulation without the cemu window closing.
I would like it to stay open so that I can change the game without having to restart this

**Comment by Exzap** [comment] 2024-07-05 11:40
Duplicate of #219

**Closed by Exzap** 2024-07-05 11:40 UTC
Labels: feature request

**Comment by wandpro** [comment] 2024-07-05 13:29
?
