### ISSUE TITLE
Pokemon Rumble U Black Screen

### ISSUE THREAD

**Issue by TylerJaacks** [cemu-project/Cemu#686] opened 2023-03-06 04:33 UTC
Cemu Version: 2.0-28
Specs: RTX 2080 Ti | 5950X | 64GB | Windows 11 22H2

When loading into a new level in Pokemon Rumble [TitleId: 00050000-10147700] [v0] there is a Black Screen this happens in both Vulkan and OpenGL. This game has worked in older versions of Cemu around 2 to 3 years ago.

![Screenshot 2023-03-05 222705](https://user-images.githubusercontent.com/1505374/223019490-20fdc479-f4c1-4e64-9565-93949b2397d0.png)

**Comment by Squall-Leonhart** [comment] 2023-03-06 05:08
if it works in -27, the issue is already known.

**Comment by Squall-Leonhart** [comment] 2023-03-06 23:59
https://github.com/cemu-project/Cemu/releases/tag/v2.0-27

**Comment by user18081972** [comment] 2023-03-11 15:40
> if it works in -27, the issue is already known.
The same issue occurs in v2.0-27, and also v1.26.2f
![image](https://user-images.githubusercontent.com/124319511/224491933-0c0078d9-2325-484d-bac8-8614fcbb657a.png)
![image](https://user-images.githubusercontent.com/124319511/224492158-af2c3ff8-6257-4694-9543-3842d6e92a0e.png)

It has been reported as early  as v1.16.1 https://wiki.cemu.info/wiki/Pok%C3%A9mon_Rumble_U
Here is a video from 2020 with the same issue: https://www.youtube.com/watch?v=JMSMsaw6xAk

Someone in the discord said the following about the bug:
"Arnie - 01/23/2022 1:33 AM
it uses unimplemented functions
or there is a race condition (I can't remember what was said about that game specifically when I asked about it a few months ago) that causes it to crash"

**Comment by TylerJaacks** [comment] 2023-03-12 07:17
Is this related to Amiibo then?

**Comment by user18081972** [comment] 2023-03-12 22:12
the game has optional Amiibo integration, so it is likely.

**Comment by Squall-Leonhart** [comment] 2023-03-12 22:30
amiibo's are fine on cemu.

**Comment by MonochromeKirby** [comment] 2023-04-06 20:17
> [16:43:59.215] Unsupported lib call: ntag.NTAGIsInit
> [16:43:59.215] Unsupported lib call: ntag.NTAGInit
> [16:43:59.215] Unsupported lib call: ntag.NTAGSetTagDetectCallback
> [16:43:59.215] Unsupported lib call: ntag.NTAGSetFormatSettings

I didn't receive anything like this on 2.0-32. The "NFC Figure" option on the title screen works fine, even if scanning the figures themselves is currently impossible. However, every level crashes upon entry and not just the first one (I tested this using a save file with the main story completed).

**Comment by Litbolt123** [comment] 2024-04-09 21:20
I am having the same issue :/

**Comment by GaryOderNichts** [comment] 2024-05-23 07:59
Should be fixed with Cemu 2.0-83.

**Comment by Litbolt123** [comment] 2024-05-23 10:59
Yay! Thanks!

**Closed** 2024-06-06 03:14 UTC
