### ISSUE TITLE
[Building, Windows x64, VS] LNK1181 cannot open input file 'speexdsp.lib'

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [cemu-project/Cemu#1281] opened 2024-08-04 20:38 UTC
### Current Behavior

I'm currently to unable to build Cemu from the latest commit with this exact error when executable linking happens
I have not built Cemu prior to this commit, and I have followed the wiki in order to set-up build environment

![image](https://github.com/user-attachments/assets/a9f46789-2154-457c-8d94-38ebb60d1f36)

### Expected Behavior

Executable to be linked properly

### Steps to Reproduce

1. Recursively clone this repository
2. Open the cloned folder in VS
3. Build either as 'Release' or 'RelWithDebug'

### System Info (Optional)

OS: Windows 11 build 26100
CL: Visual Studio 2022
Source: latest (main)

**Comment by Squall-Leonhart** [comment] 2024-08-04 22:50
this lib is provided with vcpkg, and cemu builds just fine here, reinit your git submodules and update them recursively.

**Comment by Exzap** [comment] 2024-08-12 15:55
Closing this because I cannot reproduce it and there is not enough info to troubleshoot this. Our current build configuration does not rely on `speexdsp.lib` ([it's explicitly disabled](https://github.com/cemu-project/Cemu/blob/9812a47cb182331f7c7c7a6a16eff014098a6206/CMakeLists.txt#L217)). Most likely something went wrong during cloning. I recommend starting from scratch and following the exact steps in the [build instructions](https://github.com/cemu-project/Cemu/blob/main/BUILD.md#windows).

If after doing this you still run into the same problem then feel free to open a new issue, but please provide all of the commands and logs.

**Closed by Exzap** 2024-08-12 15:55 UTC
Labels: bug
