### ISSUE TITLE
Vulkan pipeline corruption in current CEMU builds for MacOS (2.0.999999 experimental) when running BOTW

### ISSUE THREAD

**Issue by BgitSand** [cemu-project/Cemu#406] opened 2022-10-24 03:12 UTC
System specs:
Macbook Air M1, 16gb RAM
Ventura MacOS 13 RC
Current Bulld: CEMU 2.0.999999 experimental  Commit [4561a69] (Exzap)

After starting BOTW for the first time, all pipelines and shaders load ok. But after sometime, running BOTW at a another session (after a number of BOTW gaming sessions) randomly causes CEMU to crash. Log shows "Failed to create graphics pipeline". Have to delete shadercache folder to make BOTW run again. This has been happening on all experimental builds I used.

Log:
10:06:48.715] ------- Init Cemu 2.0-999999 (experimental) -------
[10:06:48.715] Init Wii U memory space (base: 0x00000002027e2000)
[10:06:48.715] mlc01 path: /Users/user/Library/Application Support/Cemu/mlc01
[10:06:48.715] Used CPU extensions: SSSE3, SSE4.1, AES-NI
[10:06:48.715] IOSU_CRYPTO: No otp.bin found. Online mode cannot be used
[10:06:48.715] IOSU_CRYPTO: No Seeprom.bin found. Online mode cannot be used
[10:06:48.727] Failed to read valid PlayDiary header
[10:06:53.225] Mounting title 00050000101c9400
[10:06:53.225] Base: /Users/user/Documents/BOTW Cemu/The Legend of Zelda Breath of the Wild [ALZE01] [Folder]
[10:06:53.225] Update: /Users/user/Documents/BOTW Cemu/The Legend of Zelda Breath of the Wild (UPDATE DATA) (v208) (3.243 GB) (USA) (unpacked) [Folder]
[10:06:53.225] DLC: /Users/user/Documents/BOTW Cemu/The Legend of Zelda Breath of the Wild (DLC) (2.182 GB) (USA) (unpacked) [Folder]
[10:06:53.772] COS: System fonts found. Generated shareddata (26609KB)
[10:06:53.778] ------- Init Vulkan graphics backend -------
[10:06:53.779] Vulkan instance version: 1.2
[10:06:53.780] Using GPU: Apple M1
[10:06:53.780] Driver version: 1.2.0
[10:06:53.780] VK_EXT_custom_border_color not supported. Cannot emulate arbitrary border color
[10:06:53.780] VulkanLimits: UBAlignment 16 nonCoherentAtomSize 16
[10:06:53.785] Using available debug function: vkCreateDebugUtilsMessengerEXT()
[10:06:53.785] Vulkan device memory info:
[10:06:53.785] Heap 0 - Size 16384MB Flags 0x00000001
[10:06:53.785] Memory 0 - HeapIndex 0 Flags 0x00000001
[10:06:53.785] Memory 1 - HeapIndex 0 Flags 0x0000000f
[10:06:53.785] Memory 2 - HeapIndex 0 Flags 0x0000000b
[10:06:53.785] Memory 3 - HeapIndex 0 Flags 0x00000011
[10:06:53.785] VK_FORMAT_D24_UNORM_S8_UINT not supported
[10:06:53.785] VK_FORMAT_R4G4B4A4_UNORM_PACK16 not supported
[10:06:53.785] VK_FORMAT_R4G4_UNORM_PACK8 not supported
[10:06:53.785] VK_FORMAT_R5G6B5_UNORM_PACK16 not supported
[10:06:53.785] VK_FORMAT_R5G5B5A1_UNORM_PACK16 not supported
[10:06:53.790] Vulkan: Can't find mailbox present mode
[10:06:53.792] ------- Loaded title -------
[10:06:53.792] TitleId: 00050000-101c9400
[10:06:53.792] TitleVersion: v208
[10:06:53.792] TitleRegion: US
[10:06:53.792] Save path:   /Users/user/Library/Application Support/Cemu/mlc01/usr/save/00050000/101C9400/user/
[10:06:53.792] Shader cache file: shaderCache/transferable/00050000101c9400.bin
[10:06:53.792] gameprofile path: gameProfiles/default/00050000101c9400.ini
[10:06:53.792] RPX hash (updated): fb7911ad
[10:06:53.792] RPX hash (base): dcac9927
[10:06:53.792] Graphic pack: Using modified RAM mapping 10000000-a0000000 (+1310720KiB)
[10:06:53.792] Graphic pack: Using modified RAM mapping a0000000-e0000000 (+589824KiB)
[10:06:53.922] Loaded module 'u-king' with checksum 0x6267bfd0
[10:06:53.922] RPL link time: 128ms
[10:06:54.065] HLE scan time: 143ms
[10:06:54.065] ------- Active settings -------
[10:06:54.065] CPU-Mode: Multi-core recompiler
[10:06:54.065] Load shared libraries: true
[10:06:54.065] Use precompiled shaders: auto (gameprofile)
[10:06:54.065] Full sync at GX2DrawDone: true
[10:06:54.065] Async compile: false
[10:06:54.065] Console language: English
[10:06:54.073] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:06:54.174] ------- Activate graphic packs -------
[10:06:54.176] Applying patch group 'BotW_InfiniteAmiibo_V208'
[10:06:54.176] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Amiibo
[10:06:54.176] Applying patch group 'BotW_InfiniteStamina_V208'
[10:06:54.176] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Stamina
[10:06:54.176] Applying patch group 'BotW_InfiniteUrbosa_V208'
[10:06:54.176] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Urbosa's Fury
[10:06:54.178] Vulkan: Can't find mailbox present mode
[10:06:54.178] Applying patch group 'BotW_ArrowDrawSpeed_V208'
[10:06:54.179] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Arrow Draw Speed [Presets: 1x (Default)]
[10:06:54.179] Applying patch group 'BotW_Durability_V208' (Codecave: 01800000-01800004)
[10:06:54.179] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Durability [Presets: x1 (Default)]
[10:06:54.179] Applying patch group '9999StampsLimit'
[10:06:54.179] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/9999 Map Stamps Limit
[10:06:54.180] Applying patch group 'BotW_InfiniteDaruk_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Daruk's Protection
[10:06:54.180] Applying patch group 'BotW_InfiniteMotorcycleEnergy_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Motorcycle Energy
[10:06:54.180] Applying patch group 'BotW_InfiniteRevali_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Revali's Gale
[10:06:54.180] Applying patch group 'BotW_InfiniteMipha_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Mipha's Grace
[10:06:54.180] Vulkan: Can't find mailbox present mode
[10:06:54.180] Applying patch group 'BotW_MotorcycleAllRegions_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Spawn Motorcycle In All Regions
[10:06:54.180] Applying patch group 'BotW_InfiniteHearts_V208'
[10:06:54.180] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Hearts
[10:06:54.181] Applying patch group 'BotwMasterModeOptionsV208'
[10:06:54.181] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Master Mode Options [Presets: Disabled (Default),Disabled (Default),Enabled (Default),Enabled (Default),Enabled (Default),Enabled (Default),Enabled (Default),Enabled (Default),Disabled (Default)]
[10:06:54.181] Applying patch group 'BotW_InfiniteArrows_V208'
[10:06:54.181] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Cheats/Infinite Arrows
[10:06:54.186] Applying patch group 'BotW_Gamespeed_V208' (Codecave: 01800100-018003d0)
[10:06:54.186] Applying patch group 'BotW_Ragdolls_V208' (Codecave: 01800400-01800410)
[10:06:54.186] Applying patch group 'BotW_FenceMethod_V208' (Codecave: 01800500-0180056c)
[10:06:54.186] Applying patch group 'BotW_Cutscene_V208' (Codecave: 01800600-01800838)
[10:06:54.186] Applying patch group 'BotW_VSync_V208' (Codecave: 01800900-018009a4)
[10:06:54.186] Applying patch group 'BotW_ControllerScrollSpeed_V208' (Codecave: 01800a00-01800ddc)
[10:06:54.186] Applying patch group 'BotW_WaterPhysics_V208' (Codecave: 01800e00-01800e38)
[10:06:54.186] Applying patch group 'BotW_LoadingScreen_V208'
[10:06:54.186] Applying patch group 'BotW_KorokChasing_V208' (Codecave: 01800f00-01800f20)
[10:06:54.186] Set vsync frequency to 500 (graphic pack The Legend of Zelda: Breath of the Wild/Mods/FPS++)
[10:06:54.186] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Mods/FPS++ [Presets: Advanced Settings,60FPS Limit (Default),No FPS Limit (for benchmarking),Automatically Limit In Few Cutscenes (Recommended),Disabled (Default, dynamically adjust game speed),8 Frames Averaged (Default),Performance Fence (Default),Disabled (Default)]
[10:06:54.186] Applying patch group 'BotW_ExtendedMemory_V208'
[10:06:54.186] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Mods/Extended Memory
[10:06:54.187] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Enhancements [Presets: t3nka Neutral+,Enabled,Normal Reflections,Low (4 samples, Default),Ultra (8x, Default)]
[10:06:54.202] Applying patch group 'BotW_GUIAspectRatio_V208' (Codecave: 01801000-01803398)
[10:06:54.202] Applying patch group 'BotW_AspectRatio_Shared' (Codecave: 01803400-01803408)
[10:06:54.202] Applying patch group 'BotW_AspectRatio_V208'
[10:06:54.202] Applying patch group 'BotW_GUIScreenNames_V208' (Codecave: 01803500-0180447f)
[10:06:54.205] Activate graphic pack: The Legend of Zelda: Breath of the Wild/Graphics [Presets: 16:9 (Default),1280x720 (HD, Default),Edge HUD (Default),Normal FXAA (Default),Medium (100%, Default),High (Default)]
[10:06:54.205] ------- Init Audio backend -------
[10:06:54.205] DirectSound: not supported
[10:06:54.205] XAudio 2.8: not supported
[10:06:54.205] XAudio 2.7: not supported
[10:06:54.205] Cubeb: available
[10:06:54.205] ------- Run title -------
[10:06:54.317] Recompiler initialized. CPU extensions: 
[10:06:54.339] IOSU_ACT: using account default in first slot
[10:06:59.126] Vulkan: Can't find mailbox present mode
[10:07:00.588] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:08.619] Failed to create graphics pipeline. Error -3
[10:07:08.629] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:09.171] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:09.898] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:09.998] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:23.104] Failed to create graphics pipeline. Error -3
[10:07:23.201] Failed to create graphics pipeline. Error -3
[10:07:23.217] Failed to create graphics pipeline. Error -3
[10:07:23.232] Failed to create graphics pipeline. Error -3
[10:07:23.245] Failed to create graphics pipeline. Error -3
[10:07:23.245] Failed to create graphics pipeline. Error -3
[10:07:23.289] Failed to create graphics pipeline. Error -3
[10:07:23.313] Failed to create graphics pipeline. Error -3
[10:07:23.594] Failed to create graphics pipeline. Error -3
[10:07:23.964] Failed to create graphics pipeline. Error -3
[10:07:24.026] Failed to create graphics pipeline. Error -3
[10:07:24.048] Failed to create graphics pipeline. Error -3
[10:07:24.115] Failed to create graphics pipeline. Error -3
[10:07:24.116] Failed to create graphics pipeline. Error -3
[10:07:24.546] Failed to create graphics pipeline. Error -3
[10:07:24.728] Failed to create graphics pipeline. Error -3
[10:07:24.863] Failed to create graphics pipeline. Error -3
[10:07:24.867] Failed to create graphics pipeline. Error -3
[10:07:24.879] Failed to create graphics pipeline. Error -3
[10:07:24.892] Failed to create graphics pipeline. Error -3
[10:07:24.967] Failed to create graphics pipeline. Error -3
[10:07:24.994] Failed to create graphics pipeline. Error -3
[10:07:25.056] Failed to create graphics pipeline. Error -3
[10:07:25.105] Failed to create graphics pipeline. Error -3
[10:07:25.115] Failed to create graphics pipeline. Error -3
[10:07:25.130] Failed to create graphics pipeline. Error -3
[10:07:25.654] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:32.068] Failed to create graphics pipeline. Error -3
[10:07:36.493] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:07:36.614] Failed to create graphics pipeline. Error -3
[10:07:36.618] Failed to create graphics pipeline. Error -3
[10:07:36.619] Failed to create graphics pipeline. Error -3
[10:07:36.620] Failed to create graphics pipeline. Error -3
[10:07:36.620] Failed to create graphics pipeline. Error -3
[10:07:36.621] Failed to create graphics pipeline. Error -3
[10:07:36.622] Failed to create graphics pipeline. Error -3
[10:07:36.760] Failed to create graphics pipeline. Error -3
[10:07:36.760] Failed to create graphics pipeline. Error -3
[10:07:41.886] Failed to create graphics pipeline. Error -3
[10:08:43.596] Failed to create graphics pipeline. Error -3
[10:08:43.828] Failed to create graphics pipeline. Error -3
[10:08:43.862] Failed to create graphics pipeline. Error -3
[10:08:43.882] Failed to create graphics pipeline. Error -3
[10:08:43.912] Failed to create graphics pipeline. Error -3
[10:08:43.912] Failed to create graphics pipeline. Error -3
[10:08:44.033] Failed to create graphics pipeline. Error -3
[10:08:44.111] Failed to create graphics pipeline. Error -3
[10:08:44.398] Failed to create graphics pipeline. Error -3
[10:08:44.479] Failed to create graphics pipeline. Error -3
[10:08:44.503] Failed to create graphics pipeline. Error -3
[10:08:44.583] Failed to create graphics pipeline. Error -3
[10:08:48.882] Failed to create graphics pipeline. Error -3
[10:08:48.946] Failed to create graphics pipeline. Error -3
[10:08:48.966] Failed to create graphics pipeline. Error -3
[10:08:48.984] Failed to create graphics pipeline. Error -3
[10:08:49.001] Failed to create graphics pipeline. Error -3
[10:08:49.034] Failed to create graphics pipeline. Error -3
[10:08:53.033] Failed to create graphics pipeline. Error -3
[10:08:53.078] Failed to create graphics pipeline. Error -3
[10:08:53.097] Failed to create graphics pipeline. Error -3
[10:08:53.116] Failed to create graphics pipeline. Error -3
[10:08:55.990] Failed to create graphics pipeline. Error -3
[10:08:56.029] Failed to create graphics pipeline. Error -3
[10:08:56.230] Failed to create graphics pipeline. Error -3
[10:08:56.270] Failed to create graphics pipeline. Error -3
[10:08:56.270] Failed to create graphics pipeline. Error -3
[10:08:57.069] Failed to create graphics pipeline. Error -3
[10:09:16.821] Failed to create graphics pipeline. Error -3
[10:09:17.094] Failed to create graphics pipeline. Error -3
[10:09:17.201] Failed to create graphics pipeline. Error -3
[10:09:17.228] Failed to create graphics pipeline. Error -3
[10:09:35.990] Failed to create graphics pipeline. Error -3
[10:09:35.997] Failed to create graphics pipeline. Error -3
[10:09:36.062] Failed to create graphics pipeline. Error -3
[10:09:36.068] Failed to create graphics pipeline. Error -3
[10:09:36.611] Failed to create graphics pipeline. Error -3
[10:09:36.630] Failed to create graphics pipeline. Error -3
[10:09:36.660] Failed to create graphics pipeline. Error -3
[10:09:36.661] Failed to create graphics pipeline. Error -3
[10:09:36.814] Failed to create graphics pipeline. Error -3
[10:09:36.848] Failed to create graphics pipeline. Error -3
[10:09:37.198] Failed to create graphics pipeline. Error -3
[10:09:37.202] Failed to create graphics pipeline. Error -3
[10:09:37.202] Failed to create graphics pipeline. Error -3
[10:09:37.230] Failed to create graphics pipeline. Error -3
[10:09:37.262] Failed to create graphics pipeline. Error -3
[10:09:37.362] Failed to create graphics pipeline. Error -3
[10:09:37.363] Failed to create graphics pipeline. Error -3
[10:09:37.364] Failed to create graphics pipeline. Error -3
[10:09:37.364] Failed to create graphics pipeline. Error -3
[10:09:37.366] Failed to create graphics pipeline. Error -3
[10:09:37.391] Failed to create graphics pipeline. Error -3
[10:09:37.611] Failed to create graphics pipeline. Error -3
[10:09:37.671] Failed to create graphics pipeline. Error -3
[10:09:37.749] Failed to create graphics pipeline. Error -3
[10:09:37.814] Failed to create graphics pipeline. Error -3
[10:09:37.815] Failed to create graphics pipeline. Error -3
[10:09:37.841] Failed to create graphics pipeline. Error -3
[10:09:37.841] Failed to create graphics pipeline. Error -3
[10:09:37.868] Failed to create graphics pipeline. Error -3
[10:09:37.893] Failed to create graphics pipeline. Error -3
[10:09:40.839] Failed to create graphics pipeline. Error -3
[10:09:40.853] Failed to create graphics pipeline. Error -3
[10:09:48.093] Failed to create graphics pipeline. Error -3
[10:09:48.094] Failed to create graphics pipeline. Error -3
[10:10:00.002] Failed to create graphics pipeline. Error -3
[10:10:00.088] Failed to create graphics pipeline. Error -3
[10:10:00.104] Failed to create graphics pipeline. Error -3
[10:10:00.113] Failed to create graphics pipeline. Error -3
[10:10:00.125] Failed to create graphics pipeline. Error -3
[10:10:00.126] Failed to create graphics pipeline. Error -3
[10:10:00.153] Failed to create graphics pipeline. Error -3
[10:10:00.183] Failed to create graphics pipeline. Error -3
[10:10:00.257] Failed to create graphics pipeline. Error -3
[10:10:00.284] Failed to create graphics pipeline. Error -3
[10:10:00.318] Failed to create graphics pipeline. Error -3
[10:12:30.169] Failed to create graphics pipeline. Error -3
[10:12:30.175] Failed to create graphics pipeline. Error -3
[10:12:30.314] Failed to create graphics pipeline. Error -3
[10:12:30.672] Failed to create graphics pipeline. Error -3
[10:12:30.761] Failed to create graphics pipeline. Error -3
[10:12:30.769] Failed to create graphics pipeline. Error -3
[10:13:52.730] Failed to create graphics pipeline. Error -3
[10:13:52.745] Failed to create graphics pipeline. Error -3
[10:13:52.760] Failed to create graphics pipeline. Error -3
[10:13:52.775] Failed to create graphics pipeline. Error -3
[10:13:52.790] Failed to create graphics pipeline. Error -3
[10:13:52.805] Failed to create graphics pipeline. Error -3
[10:13:52.821] Failed to create graphics pipeline. Error -3
[10:13:52.839] Failed to create graphics pipeline. Error -3
[10:13:52.844] Failed to create graphics pipeline. Error -3
[10:13:52.861] Failed to create graphics pipeline. Error -3
[10:13:52.869] Failed to create graphics pipeline. Error -3
[10:13:52.870] Failed to create graphics pipeline. Error -3
[10:13:52.907] Failed to create graphics pipeline. Error -3
[10:13:52.929] Failed to create graphics pipeline. Error -3
[10:13:52.939] Failed to create graphics pipeline. Error -3
[10:13:52.962] Failed to create graphics pipeline. Error -3
[10:13:52.985] Failed to create graphics pipeline. Error -3
[10:13:53.008] Failed to create graphics pipeline. Error -3
[10:13:53.030] Failed to create graphics pipeline. Error -3
[10:13:53.054] Failed to create graphics pipeline. Error -3
[10:13:53.055] Failed to create graphics pipeline. Error -3
[10:13:53.063] Failed to create graphics pipeline. Error -3
[10:13:53.063] Failed to create graphics pipeline. Error -3
[10:13:53.073] Failed to create graphics pipeline. Error -3
[10:13:53.074] Failed to create graphics pipeline. Error -3
[10:13:53.075] Failed to create graphics pipeline. Error -3
[10:13:53.110] Failed to create graphics pipeline. Error -3
[10:13:53.134] Failed to create graphics pipeline. Error -3
[10:13:53.148] Failed to create graphics pipeline. Error -3
[10:13:53.149] Failed to create graphics pipeline. Error -3
[10:15:11.846] Failed to create graphics pipeline. Error -3
[10:15:11.847] Failed to create graphics pipeline. Error -3
[10:15:11.863] Failed to create graphics pipeline. Error -3
[10:15:11.880] Failed to create graphics pipeline. Error -3
[10:15:11.885] Failed to create graphics pipeline. Error -3
[10:15:11.936] Failed to create graphics pipeline. Error -3
[10:15:11.937] Failed to create graphics pipeline. Error -3
[10:15:11.956] Failed to create graphics pipeline. Error -3
[10:15:11.980] Failed to create graphics pipeline. Error -3
[10:15:50.418] Failed to create graphics pipeline. Error -3
[10:15:50.442] Failed to create graphics pipeline. Error -3
[10:17:10.464] Failed to create graphics pipeline. Error -3
[10:17:10.566] Failed to create graphics pipeline. Error -3
[10:17:11.015] Failed to create graphics pipeline. Error -3
[10:17:13.237] Failed to create graphics pipeline. Error -3
[10:18:01.438] Failed to create graphics pipeline. Error -3
[10:21:44.677] Failed to create graphics pipeline. Error -3
[10:22:31.600] Failed to create graphics pipeline. Error -3
[10:23:20.861] Failed to create graphics pipeline. Error -3
[10:23:20.867] Failed to create graphics pipeline. Error -3
[10:25:59.346] Failed to create graphics pipeline. Error -3
[10:25:59.408] Failed to create graphics pipeline. Error -3
[10:25:59.461] Failed to create graphics pipeline. Error -3
[10:25:59.574] Failed to create graphics pipeline. Error -3
[10:25:59.731] Failed to create graphics pipeline. Error -3
[10:25:59.781] Failed to create graphics pipeline. Error -3
[10:26:00.036] Failed to create graphics pipeline. Error -3
[10:26:22.759] Failed to create graphics pipeline. Error -1000012000
[10:26:41.379] Failed to create graphics pipeline. Error -3
[10:26:41.399] Failed to create graphics pipeline. Error -3
[10:26:41.473] Failed to create graphics pipeline. Error -3
[10:26:41.497] Failed to create graphics pipeline. Error -3
[10:26:41.522] Failed to create graphics pipeline. Error -3
[10:26:41.766] Failed to create graphics pipeline. Error -3
[10:26:41.863] Failed to create graphics pipeline. Error -3
[10:26:41.882] Failed to create graphics pipeline. Error -3
[10:26:41.919] Failed to create graphics pipeline. Error -3
[10:26:41.937] Failed to create graphics pipeline. Error -3
[10:26:45.141] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:26:46.584] Failed to create graphics pipeline. Error -3
[10:26:46.593] Failed to create graphics pipeline. Error -3
[10:26:46.672] Failed to create graphics pipeline. Error -3
[10:26:46.691] Failed to create graphics pipeline. Error -3
[10:27:12.334] Vulkan-Info: Allocated additional memory for textures from device-local memory
[10:27:37.213] Failed to create graphics pipeline. Error -3
[10:27:39.288] Failed to create graphics pipeline. Error -3
[10:27:39.289] Failed to create graphics pipeline. Error -3
[10:27:39.322] Failed to create graphics pipeline. Error -3
[10:27:39.350] Failed to create graphics pipeline. Error -3
[10:27:39.679] Failed to create graphics pipeline. Error -3
[10:27:49.530] Failed to create graphics pipeline. Error -3
[10:27:49.551] Failed to create graphics pipeline. Error -3
[10:27:50.018] Failed to create graphics pipeline. Error -3
[10:29:15.527] Failed to create graphics pipeline. Error -3
[10:29:55.281] Failed to create graphics pipeline. Error -1000012000
[10:29:55.282] Failed to create graphics pipeline. Error -1000012000
[10:29:55.438] Failed to create graphics pipeline. Error -1000012000
[10:31:38.341] Failed to create graphics pipeline. Error -1000012000
[10:31:47.805] Failed to create graphics pipeline. Error -3
[10:31:48.195] Failed to create graphics pipeline. Error -3
[10:33:52.625] Failed to create graphics pipeline. Error -3
[10:33:53.813] Failed to create graphics pipeline. Error -3
[10:33:54.160] Failed to create graphics pipeline. Error -3

**Comment by Squall-Leonhart** [comment] 2022-10-24 03:51
duplicate of #396?

**Comment by BgitSand** [comment] 2022-10-24 03:59
> duplicate of #396?

I guess I should have put this under #396. Mine does not crash after second run of CEMU and BOTW as reported in #396, but randomly on later gaming sessions. It runs very well for a number of gaming sessions before the crash happens.

**Comment by Mercen-Lee** [comment] 2022-10-25 02:31
Same error

[11:28:12.229] ------- Init Cemu 2.0-8 (experimental) -------
[11:28:12.229] Init Wii U memory space (base: 0x0000000202c6d000)
[11:28:12.229] mlc01 path: /Users/mercen/Library/Application Support/Cemu/mlc01
[11:28:12.229] Used CPU extensions: SSSE3, SSE4.1, AES-NI
[11:28:12.229] IOSU_CRYPTO: No otp.bin found. Online mode cannot be used
[11:28:12.229] IOSU_CRYPTO: No Seeprom.bin found. Online mode cannot be used
[11:28:12.243] PlayStats.dat malformed
[11:28:12.243] Failed to read valid PlayDiary header
[11:28:13.847] Mounting title 00050000101c9300
[11:28:13.848] Base: /Users/mercen/Library/Application Support/Cemu/mlc01/usr/title/00050000/101c9300 [Folder]
[11:28:13.848] Update: /Users/mercen/Library/Application Support/Cemu/mlc01/usr/title/0005000e/101c9300 [Folder]
[11:28:13.848] DLC: /Users/mercen/Library/Application Support/Cemu/mlc01/usr/title/0005000c/101c9300 [Folder]
[11:28:14.397] COS: System fonts found. Generated shareddata (26609KB)
[11:28:14.403] ------- Init Vulkan graphics backend -------
[11:28:14.404] Vulkan instance version: 1.2
[11:28:14.409] Using GPU: Apple M1 Pro
[11:28:14.409] Driver version: 1.2.0
[11:28:14.409] VK_EXT_custom_border_color not supported. Cannot emulate arbitrary border color
[11:28:14.409] VulkanLimits: UBAlignment 16 nonCoherentAtomSize 16
[11:28:14.426] Using available debug function: vkCreateDebugUtilsMessengerEXT()
[11:28:14.426] Vulkan device memory info:
[11:28:14.426] Heap 0 - Size 16384MB Flags 0x00000001
[11:28:14.426] Memory 0 - HeapIndex 0 Flags 0x00000001
[11:28:14.426] Memory 1 - HeapIndex 0 Flags 0x0000000f
[11:28:14.426] Memory 2 - HeapIndex 0 Flags 0x0000000b
[11:28:14.426] Memory 3 - HeapIndex 0 Flags 0x00000011
[11:28:14.426] VK_FORMAT_D24_UNORM_S8_UINT not supported
[11:28:14.426] VK_FORMAT_R4G4B4A4_UNORM_PACK16 not supported
[11:28:14.426] VK_FORMAT_R4G4_UNORM_PACK8 not supported
[11:28:14.426] VK_FORMAT_R5G6B5_UNORM_PACK16 not supported
[11:28:14.426] VK_FORMAT_R5G5B5A1_UNORM_PACK16 not supported
[11:28:15.119] ------- Loaded title -------
[11:28:15.119] TitleId: 00050000-101c9300
[11:28:15.119] TitleVersion: v208
[11:28:15.119] TitleRegion: JP
[11:28:15.120] Save path:   /Users/mercen/Library/Application Support/Cemu/mlc01/usr/save/00050000/101C9300/user/
[11:28:15.120] Shader cache file: shaderCache/transferable/00050000101c9300.bin
[11:28:15.120] gameprofile path: gameProfiles/default/00050000101c9300.ini
[11:28:15.120] RPX hash (updated): fb7911ad
[11:28:15.120] RPX hash (base): dcac9927
[11:28:15.269] Loaded module 'u-king' with checksum 0x6267bfd0
[11:28:15.269] RPL link time: 145ms
[11:28:15.406] HLE scan time: 137ms
[11:28:15.406] ------- Active settings -------
[11:28:15.406] CPU-Mode: Multi-core recompiler
[11:28:15.406] Load shared libraries: true
[11:28:15.406] Use precompiled shaders: auto (gameprofile)
[11:28:15.406] Full sync at GX2DrawDone: true
[11:28:15.406] Async compile: false
[11:28:15.406] Console language: English
[11:28:15.438] Vulkan-Info: Allocated additional memory for textures from device-local memory
[11:28:15.546] ------- Activate graphic packs -------
[11:28:15.546] ------- Init Audio backend -------
[11:28:15.546] DirectSound: not supported
[11:28:15.546] XAudio 2.8: not supported
[11:28:15.546] XAudio 2.7: not supported
[11:28:15.546] Cubeb: available
[11:28:15.546] ------- Run title -------
[11:28:15.839] Failed to create graphics pipeline. Error -3
[11:28:17.980] Failed to create graphics pipeline. Error -3
[11:28:17.994] Failed to create graphics pipeline. Error -3
[11:28:18.192] Failed to create graphics pipeline. Error -3
[11:28:18.197] Failed to create graphics pipeline. Error -3
[11:28:18.283] Failed to create graphics pipeline. Error -3
[11:28:18.283] Failed to create graphics pipeline. Error -3
[11:28:18.348] Failed to create graphics pipeline. Error -3
[11:28:18.354] Failed to create graphics pipeline. Error -3
[11:28:18.431] Failed to create graphics pipeline. Error -3
[11:28:18.431] Failed to create graphics pipeline. Error -3
[11:28:18.431] Failed to create graphics pipeline. Error -3
[11:28:18.431] Failed to create graphics pipeline. Error -3
[11:28:18.432] Failed to create graphics pipeline. Error -3
[11:28:18.434] Failed to create graphics pipeline. Error -3
[11:28:18.448] Failed to create graphics pipeline. Error -3
[11:28:18.452] Failed to create graphics pipeline. Error -3
[11:28:18.478] Failed to create graphics pipeline. Error -3
[11:28:18.483] Failed to create graphics pipeline. Error -3
[11:28:18.492] Failed to create graphics pipeline. Error -3

**Comment by Mercen-Lee** [comment] 2022-10-25 02:43
Did you modify the resolution with the graphic pack?

**Comment by BgitSand** [comment] 2022-10-25 05:43
> Did you modify the resolution with the graphic pack?

I only used the default "1280x720" HD in the graphics pack.

**Comment by Mercen-Lee** [comment] 2022-10-25 23:46
> > Did you modify the resolution with the graphic pack?
> 
> I only used the default "1280x720" HD in the "Graphics" section of the graphic pack. Should I toggle OFF the "Graphics" section in the graphic pack?

Have you tried removing the shader cache folder?

**Comment by BgitSand** [comment] 2022-10-26 06:36
I only used the default 1280x720 resolution.

**Comment by BgitSand** [comment] 2022-10-26 08:45
> 

Deleting the shadercache folder is the only way to deal with the bug so you are able to run BOTW again.

**Comment by BgitSand** [comment] 2022-10-26 08:46
> > > Did you modify the resolution with the graphic pack?
> > 
> > 
> > I only used the default "1280x720" HD in the "Graphics" section of the graphic pack. Should I toggle OFF the "Graphics" section in the graphic pack?
> 
> Have you tried removing the shader cache folder?

Deleting the shadercache folder is the only way to deal with the bug so you are able to run BOTW again.

**Comment by Exzap** [comment] 2022-10-26 12:31
Closing this since it's a duplicate of #396

**Closed by Exzap** 2022-10-26 12:31 UTC

**Comment by BgitSand** [comment] 2022-10-26 12:58
Sure. no problem.
