### ISSUE TITLE
Portal Of Power Not Working On MacOS

### ISSUE THREAD

**Issue by KermitPrplYT** [cemu-project/Cemu#850] opened 2023-06-07 12:53 UTC

**Comment by KermitPrplYT** [comment] 2023-06-07 12:54
I am running MacOS Ventura with a 2020 M1 Macbook Air. I cannot find solutions on why my portal isn't connecting. Are there any workarounds or is it just not possible?

**Comment by Crementif** [comment] 2023-06-07 13:50
This is a duplicate of https://github.com/cemu-project/Cemu/issues/275.

**Closed by Crementif** 2023-06-07 13:50 UTC
