### ISSUE TITLE
MacOS specific section in the menu bar are not correctly localized

### ISSUE THREAD

**Issue by AndreaCicca** [cemu-project/Cemu#1136] opened 2024-03-24 18:58 UTC
### Current Behavior

At the moment, on the latest experimental build, there are MacOS specific menus that are not correctly localized in each languages.

After @Fs00 #1133 the situation is partially improved, but it is still not the optimal situation.

This is the current situation (Cemu-73 Experimental) in the "windows" when I use the Italian localization.
I am using CEMU with the Italian language set for both the application and the operating system. 
<img width="319" alt="316314998-5302d947-7bd0-4e6d-b767-40f97aa5516d" src="https://github.com/cemu-project/Cemu/assets/58073848/5d1bd552-7d09-4165-9bea-6e0eb65d97db">

A similar situation is happening in the "Cemu" section in the menu bar, everything is displayed in English

<img width="214" alt="Screenshot 2024-03-24 alle 19 47 47" src="https://github.com/cemu-project/Cemu/assets/58073848/99ce0a2a-9c94-4355-bdbb-e9256b21797f">

This is the situation after @Fs00's PR, an improvement, but still the issue isn't completely solved.
<img width="376" alt="316315089-011fd476-25c2-49e2-856c-94bcba648b5c" src="https://github.com/cemu-project/Cemu/assets/58073848/b7aa374a-7fce-4727-be1f-99745eed6703">

For context this is how it is handled in a different [app](https://github.com/Whisky-App/Whisky)
<img width="376" alt="image" src="https://github.com/cemu-project/Cemu/assets/58073848/e70ee24f-5e5c-4f37-84e0-14dd42d2ebbe">

Everything is correctly localized in Italian.

### Expected Behavior

All MacOS specific menus within the application should be correctly localized according to the selected user language

### Steps to Reproduce

- Download latest build
- Select a language that is not English in the Cemu app.
- Open the Window or Cemu section in the menu bar

### System Info (Optional)

OS: 14.3.1 (23D60)
SOC: M1 Mac book air 
System language: Italian (for context)

**Comment by cabrerahector** [comment] 2024-03-24 20:16
Duplicate of https://github.com/cemu-project/Cemu/pull/1133?

**Closed** 2024-09-25 10:42 UTC
Labels: bug
