### ISSUE TITLE
Cemu 2.0 - Hangs w/vsync match emulated display on GTX 1060 6GB

### ISSUE THREAD

**Issue by joao-pedro-barbosa** [cemu-project/Cemu#386] opened 2022-10-18 13:46 UTC
Hi.

I'm running version 2, under last linux native version and I noticed "Match emulated display" VSync option hangs to me after compile vulkan pipelines. It doesn't do the fadeout from background game picture. It just keeps the background image after compiling vulkan pipelines and don't resume.
My setup is 
Intel i5-11400f
16G RAM DDR4
Gigabyte GTX 1060 6GB DDR5

The game I'm running is The legend of Zelda - BOTW 1.5

Thanks!

**Comment by jn64** [comment] 2022-10-18 16:06
Can repro on 15b3a3f77d8c0c6e3a95061ff337d61b198ff665

OS: Fedora 36
GPU: NVIDIA GeForce GTX 1050 Ti
Driver version: 515.76
Game: Breath of the Wild (EU, v208 / 1.5.0)

**Comment by jn64** [comment] 2022-10-23 02:46
Possibly related #203

**Comment by Exzap** [comment] 2022-11-03 00:14
Duplicate of #203

**Closed by Exzap** 2022-11-03 00:14 UTC
