### ISSUE TITLE
[Cemu-Language] : "English" resource file missing in Cemu releases causes the UI language setting to reset back to "Default" and show the "emulator should be restarted" prompt twice

### ISSUE THREAD

**Issue by Leafdomain** [cemu-project/Cemu#717] opened 2023-03-28 03:00 UTC
When I choose "English" as my UI language and save, I get the prompt that I need to restart Cemu, as expected.
Then I restart Cemu.
Then I go back to the UI language setting, it's now been changed to "Default".
I don't touch it. I close the setting. But I get the prompt again that I need to restart Cemu.
I restart Cemu again. Now I won't get the prompt again if I go to settings again. But now the setting is stuck at "Default" when it should probably stay as "English" as I had chosen.

It shouldn't be going back to "Default" after having chosen "English".

My system language is Turkish. I don't know if that has anything to do with the default detection.

I checked and confirm this is still happening on the latest version.

**Comment by mx00010** [comment] 2023-03-28 04:09
Indeed, seem if you select "English", the setting will com back to "Default" because there's no sub-folder named "en" containing a proper "cemu.mo" file in ressource folder.

Tried this : if you mockup this sub-folder named "en" with a cemu.mo file in it, the "English" setting will stay selected in the dropdown menu after the restart of Cemu.

This have been tested with 1.26.1 , 1.27.1 and more recent (2.0-29). The behavior seem there since a while. 

So, not sure if this is a real issue or maybe more an expected behavior because the "default" UI language of Cemu seem alrealy english by design. In the case, this make sense that by selecting "English" that Cemu switchs to the default language.

**Comment by Leafdomain** [comment] 2023-03-28 05:21
@mx00010
Well if it wants to stay this way, at least it shouldn't prompt the warning again.
It shows the "Cemu should be restarted" warning again after changing itself back to default, even though it had just shown that already and I had already restarted.
This makes going back to the settings cumbersome. This should be smoothed out or fixed somehow.

**Comment by mx00010** [comment] 2023-03-28 17:23
@Leafdomain 
Looking more deeply in the [Cemu-Language](https://github.com/cemu-project/Cemu-Language) ressources, seem there's a "cemu.po" (translation file) already available for English language. So, don't know why this one is not already included in cemu releases. Maybe something to add in the release packaging (?) - Again, this can be an expected behavior, but there's more doubt now that we can see a proper translation file in the code.

A suggestion is to change the title to something more like this : _[Cemu-Language] : English ressource file seem missing in Cemu releases_ or something like that.

Quick tip : to test this file an "compile/save" it from cemu.po to cemu.mo, you can just follow the available [tutorial](https://wiki.cemu.info/wiki/Tutorial:How_to_translate_Cemu_UI).

**Comment by Leafdomain** [comment] 2023-03-28 21:17
@mx00010
In any case, the emulator showing the restart prompt twice is not desired behavior and should be fixed.

Okay I'll update the title.

**Comment by mx00010** [comment] 2023-03-29 02:35
Maybe this is a side effect of this pull request : [remove redundant en language file](https://github.com/cemu-project/Cemu/pull/518). Have been commited and merged to the main branch https://github.com/cemu-project/Cemu/pull/518/commits/79e436a3e4529eefcf4ef6b29a07dedc02a3fe03

**Comment by Leafdomain** [comment] 2023-03-29 19:14
That could be what happened.
Then I could just suggest getting rid of the "Default" option perhaps, and retaining just "English"?

**Comment by mx00010** [comment] 2023-04-01 05:14
Looking in the code of [GeneralSetting2.cpp](https://github.com/cemu-project/Cemu/blob/main/src/gui/GeneralSettings2.cpp) in` wxPanel* GeneralSettings2::AddGeneralPage(wxNotebook* notebook)` function. The language dropdown menu contains an array with 2 values : "Default" at position 0 and "English" at position 1. All other languages in the dropdown menu are fetched from the ressources folder provded by ([Cemu-Language](https://github.com/cemu-project/Cemu-Language)).

```
wxString language_choices[] = { _("Default"), _("English") };
m_language = new wxChoice(box, wxID_ANY, wxDefaultPosition, wxDefaultSize, std::size(language_choices), language_choices);
m_language->SetSelection(0);
m_language->SetToolTip(_("Changes the interface language of Cemu\nAvailable languages are stored in the translation directory\nA restart will be required after changing the language"));
for (const auto& language : wxGetApp().GetLanguages())
{
m_language->Append(language->Description);
}
```
here's a screenshot if you remove all translation files in the ressources folder. So it's very easy to see the hardcoded values of the language dropdown menu.

![language](https://user-images.githubusercontent.com/128931214/229266928-ddee3e47-534f-4593-a1f9-1fd496766de9.jpg)

So,this explained why if you add a an English "cemu.po" translation file, this will add "English" as language option twice in the dropdown menu (one fetched from the language ressouces folder and the other one hardcoded. Seem the reason of this pull request : [#518](https://github.com/cemu-project/Cemu/pull/518) done by @Tillsunset where the english translation file have been removed.

So, basicaly seem there are some choices : 

1. Restore the "English" cemu.po translation file and remove the "English" hardcoded in the dropdown menu
2. Remove the "Default" hardcoded, so the hardcoded "English" can ack as the "default" language in position 0 of the array.
3. Something else (?)

In both, seem maybe this can need a little adjustements also in [CemuApp.cpp](https://github.com/cemu-project/Cemu/blob/main/src/gui/CemuApp.cpp) in  `CemuApp::OnInit()` function and  [GeneralSetting2.cpp](https://github.com/cemu-project/Cemu/blob/main/src/gui/GeneralSettings2.cpp) in `GeneralSettings2::StoreConfig()` function.

**Closed** 2023-10-16 11:41 UTC
