### ISSUE TITLE
Skylanders: SuperChargers and Imaginators are still crashing on POP initialization with Cemu 2.1

### ISSUE THREAD

**Issue by skylandersNFC** [cemu-project/Cemu#1321] opened 2024-09-01 17:45 UTC
### Current Behavior

Skylanders: SuperChargers and Imaginators still crash with Cemu 2.1 as soon as the game tries to initialize the portal of power.

This is somewhat of a continuation to https://github.com/cemu-project/Cemu/issues/1218 and https://github.com/cemu-project/Cemu/issues/1223

It seems at some point the devs messed with the portal driver and everything after [Cemu 2.0-61 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-61) have this problem.

I also tested this theory and yes, everything after Cemu 2.0-61 will instantly crash for Imaginators and SuperChargers.

Cemu won't care if you have the Emulated POP enabled or not, it will crash the moment the game (SuperChargers or Imaginators) tries to check if there is any POP available at all. 

### Expected Behavior

The SuperChargers or Imaginators not to crash after portal initialization.

### Steps to Reproduce

Just load any Skylanders: SuperChargers or Imaginators ROMs on the latest Cemu version or anything after Cemu 2.0-61 (2.0-62 onward) and see for yourself.

@deReeperJosh Do you have any ideas what was changed after Cemu v2.0-61 regarding the portal driver itself ? Thank you

**Comment by Exzap** [comment] 2024-09-01 18:33
Since the author of #1218 deleted their account I am going to close it in favor of this newer issue. But otherwise it's a duplicate.

What OS are you using? Asking since I can't replicate the crash on Windows. We use different USB backends for Linux/MacOS so it would make sense that the issue is only specific to those platforms. Does it also crash with the physical USB portal disconnected?

**Comment by skylandersNFC** [comment] 2024-09-01 20:49
We are all on Windows OS.
And by all I mean the other members on our Skylanders discord server who are also reporting this.

And yes, it does crash with the physical postal disconnected.

**Comment by deReeperJosh** [comment] 2024-09-01 21:09
I didn't think this was a portal issue, IIRC this had something to do with online connectivity, these games have also crashed on previous versions. I will do some debugging to see what causes the crashes at the menu screen but I am not sure if it will permanently fix these games

**Comment by skylandersNFC** [comment] 2024-09-01 21:27
> I didn't think this was a portal issue, IIRC this had something to do with online connectivity, these games have also crashed on previous versions. I will do some debugging to see what causes the crashes at the menu screen but I am not sure if it will permanently fix these games

Just tested this under Cemu 2.1 with Giants Portal of Power using the GIants game ==  same behavior.
For the first level of Giants, small gold changes won't be registered at all when swapping tags, until i open a chest and then the gold is instantly saved on the current tag used.
Also it seems changing hats helps, as they will trigger this save data even to the NFC dump/figure.

**Comment by deReeperJosh** [comment] 2024-09-01 23:29
I have managed to bisect the error, and the commit that seems to be causing the crash at the Superchargers/Imaginators menu is this one: https://github.com/cemu-project/Cemu/commit/bab1616565b8fab99c52e0bedb275ae90a7b53df

Will attempt to spend a bit of time understanding why this is happening

**Closed** 2024-09-02 14:20 UTC
Labels: bug
