### ISSUE TITLE
Skylanders Portal audio works, but is very broken

### ISSUE THREAD

**Issue by moonleaks** [cemu-project/Cemu#1377] opened 2024-10-12 13:04 UTC
### Current Behavior

On skylanders trap team, the portal audio now works, but its botchy and doesnt work right

### Expected Behavior

I thought the portal audio would be clear

### Steps to Reproduce

load into trap team, go to the villian vault and listen to the audio, OR put a trap in your portal and listen to the audio, OR if your on the first level and you capture gulper you'll hear the audio

**Comment by Exzap** [comment] 2024-10-12 13:26
Duplicate of #1146

**Closed by Exzap** 2024-10-12 13:26 UTC
Labels: bug

**Comment by skylandersNFC** [comment] 2024-11-21 22:40
![200w](https://github.com/user-attachments/assets/449b09f6-1823-4527-a813-233379428ec9)
