### ISSUE TITLE
spanish language broken in all 2.0 releases

### ISSUE THREAD

**Issue by rakantoh** [cemu-project/Cemu#742] opened 2023-04-02 20:41 UTC
the spanish language/translation in cemu 2.0-x is broken, always shows in english, other languages works.

and a feature request, add a option to pause/stop the actual emulation/game to open another game without close cemu

**Comment by jn64** [comment] 2023-04-02 20:48
> the spanish language/translation in cemu 2.0-x is broken, always shows in english, other languages works.

Duplicate of #506

> and a feature request, add a option to pause/stop the actual emulation/game to open another game without close cemu

Duplicate of #219

Please search before posting.

**Comment by rakantoh** [comment] 2023-04-02 21:05
ok, i forget that i already open the spanish issue, however please keep in mind fix the issues and add the features requested, thanks for the great work.

**Comment by Exzap** [comment] 2023-05-11 15:36
Spanish (and other languages) are fixed in Cemu 2.0-39

**Closed by Exzap** 2023-05-11 15:36 UTC
