### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by Twiityy** [cemu-project/Cemu#679] opened 2023-02-26 17:46 UTC
Dark Mode seems like a very good addition to Cemu, because Light Mode is very blinding in a dark environment.
There are probably some more pros to adding it, but none come to mind as of writing.

**Comment by cabrerahector** [comment] 2023-02-26 18:03
Duplicate of #120

**Closed** 2023-02-27 22:40 UTC
